# AUTOGENERATED! DO NOT EDIT!

def main(ads_manifest) -> {"ads_manifest_embed": dict, "ads_manifest_llm": dict}:
    """Broadcast ads_manifest to embedding and LLM filter nodes."""
    return {"ads_manifest_embed": ads_manifest, "ads_manifest_llm": ads_manifest}
