# AUTOGENERATED! DO NOT EDIT!

def build_onet_descriptions(onet_data, print) -> {"descriptions": dict}:
    """Build standard occupation descriptions from raw O*NET data."""
    raise NotImplementedError("build_onet_descriptions not yet implemented")
