# AUTOGENERATED! DO NOT EDIT!

def main(ctx, print) -> bool:
    """Build ASPECTT numeric vectors from O*NET database tables."""
    import numpy as np
    import pandas as pd
    
    from ai_index import const
    output_dir = const.aspectt_vectors_path
    output_dir.mkdir(parents=True, exist_ok=True)
    onet_targets = pd.read_parquet(const.onet_targets_path)
    valid_codes = set(onet_targets["O*NET-SOC Code"].tolist())
    code_to_title = dict(zip(onet_targets["O*NET-SOC Code"], onet_targets["Title"]))
    print(f"build_aspectt: {len(valid_codes)} occupations from onet_targets.parquet")
    extract_dir = const.onet_store_path / "db_30_0_text"
    
    def _load_onet_table(name):
        return pd.read_csv(extract_dir / f"{name}.txt", sep="\t", header=0, encoding="utf-8", dtype=str)
    
    CATEGORIES = [
        ("Abilities", "Element Name"),
        ("Skills", "Element Name"),
        ("Knowledge", "Element Name"),
        ("Work Activities", "Element Name"),
    ]
    
    raw_tables = {}
    for table_name, _ in CATEGORIES:
        raw_tables[table_name] = _load_onet_table(table_name)
        print(f"  loaded {table_name}: {len(raw_tables[table_name])} rows")
    def _pivot_category(df, category_name, element_col, scale_id):
        """Pivot one O*NET category table into a feature matrix for a given scale."""
        filtered = df[df["Scale ID"] == scale_id].copy()
        filtered = filtered[filtered["O*NET-SOC Code"].isin(valid_codes)]
        filtered["Data Value"] = pd.to_numeric(filtered["Data Value"], errors="coerce")
    
        pivoted = filtered.pivot_table(
            index="O*NET-SOC Code",
            columns=element_col,
            values="Data Value",
            aggfunc="sum",
        )
        # Prefix column names with category
        pivoted.columns = [f"{category_name} - {col}" for col in pivoted.columns]
        return pivoted
    
    
    level_dfs = []
    importance_dfs = []
    
    for table_name, element_col in CATEGORIES:
        df = raw_tables[table_name]
        lv = _pivot_category(df, table_name, element_col, "LV")
        im = _pivot_category(df, table_name, element_col, "IM")
        level_dfs.append(lv)
        importance_dfs.append(im)
        print(f"  {table_name}: {lv.shape[1]} features")
    
    level_matrix = pd.concat(level_dfs, axis=1)
    importance_matrix = pd.concat(importance_dfs, axis=1)
    
    # Ensure consistent row ordering — use onet_targets order
    ordered_codes = [c for c in onet_targets["O*NET-SOC Code"] if c in level_matrix.index]
    level_matrix = level_matrix.loc[ordered_codes]
    importance_matrix = importance_matrix.loc[ordered_codes]
    
    print(f"build_aspectt: level matrix {level_matrix.shape}, importance matrix {importance_matrix.shape}")
    titles = np.array([code_to_title[c] for c in ordered_codes], dtype=str)
    codes = np.array(ordered_codes, dtype=str)
    columns = np.array(level_matrix.columns.tolist(), dtype=str)
    
    np.savez(
        output_dir / "aspectt_vectors.npz",
        titles=titles,
        codes=codes,
        columns=columns,
        levels=level_matrix.values.astype(np.float32),
        importance=importance_matrix.values.astype(np.float32),
    )
    
    print(f"build_aspectt: wrote {output_dir / 'aspectt_vectors.npz'}")
    print(f"  titles: {titles.shape}")
    print(f"  codes: {codes.shape}")
    print(f"  columns: {columns.shape}")
    print(f"  levels: {level_matrix.values.shape} (float32)")
    print(f"  importance: {importance_matrix.values.shape} (float32)")
    
    return True
