# AUTOGENERATED! DO NOT EDIT!

def main(ctx, print, ad_ids: list[int], exposure_scores: "pd.DataFrame") -> {
    'ad_ids': list[int]
}:
    """Map occupation-level exposure scores to individual job ads via weighted averaging."""
    import duckdb
    import numpy as np
    import pandas as pd
    
    from ai_index import const
    run_name = ctx.vars["run_name"]
    chunk_size = ctx.vars["exposure_chunk_size"]
    
    output_dir = const.pipeline_store_path / run_name / "compute_job_ad_exposure"
    output_dir.mkdir(parents=True, exist_ok=True)
    score_cols = [c for c in exposure_scores.columns if c != "onet_code"]
    print(f"compute_job_ad_exposure: {len(score_cols)} score columns: {score_cols}")
    filtered_path = const.pipeline_store_path / run_name / "rerank_candidates" / "reranked_matches.parquet"
    conn = duckdb.connect()
    conn.execute(f"CREATE TABLE reranked AS SELECT * FROM read_parquet('{filtered_path}')")
    
    n_ads = len(ad_ids)
    n_scores = len(score_cols)
    n_chunks = (n_ads + chunk_size - 1) // chunk_size
    
    # Pre-allocate output arrays
    ad_id_to_row = {int(aid): i for i, aid in enumerate(ad_ids)}
    out_n_matches = np.zeros(n_ads, dtype=np.int32)
    out_scores = np.full((n_ads, n_scores), np.nan, dtype=np.float64)
    
    for chunk_idx in range(n_chunks):
        chunk_start = chunk_idx * chunk_size
        chunk_end = min(chunk_start + chunk_size, n_ads)
        chunk_ad_ids = ad_ids[chunk_start:chunk_end]
    
        # Load filtered matches for this chunk
        id_list = ",".join(str(int(i)) for i in chunk_ad_ids)
        chunk_matches = conn.execute(
            f"SELECT ad_id, onet_code, rerank_score "
            f"FROM reranked "
            f"WHERE ad_id IN ({id_list}) ORDER BY ad_id"
        ).fetchdf()
    
        if chunk_matches.empty:
            print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(chunk_ad_ids)} ads (no matches)")
            continue
    
        # Inner join with exposure scores (drops unrecognized onet_codes)
        merged = chunk_matches.merge(exposure_scores, on="onet_code", how="inner")
    
        if merged.empty:
            print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(chunk_ad_ids)} ads (no scores)")
            continue
    
        # Normalize rerank_score to per-ad weights
        weight_sums = merged.groupby("ad_id")["rerank_score"].transform("sum")
        merged["_weight"] = merged["rerank_score"] / weight_sums
    
        # Multiply score columns by weight, then sum per ad
        for col in score_cols:
            merged[col] = merged[col] * merged["_weight"]
    
        agg = merged.groupby("ad_id")[score_cols].sum()
        counts = merged.groupby("ad_id").size()
    
        # Write to pre-allocated arrays via index mapping
        row_indices = np.array([ad_id_to_row[int(aid)] for aid in agg.index])
        out_scores[row_indices] = agg.values
        out_n_matches[row_indices] = counts.values
    
        print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(chunk_ad_ids)} ads")
    
    conn.close()
    score_dict = {col: out_scores[:, i] for i, col in enumerate(score_cols)}
    results_df = pd.DataFrame({"ad_id": ad_ids, "n_matches": out_n_matches, **score_dict})
    results_df["error"] = np.where(out_n_matches == 0, "no matched scores", None)
    
    n_ok = int((out_n_matches > 0).sum())
    n_err = n_ads - n_ok
    
    output_path = output_dir / "ad_exposure.parquet"
    results_df.to_parquet(output_path, index=False)
    print(f"compute_job_ad_exposure: done, {n_ok} succeeded, {n_err} failed")
    print(f"  output: {const.rel(output_path)}")
    
    return ad_ids
