# AUTOGENERATED! DO NOT EDIT!

def main(onet_embed_meta, job_embed_meta, ctx, print) -> {"candidates_meta": dict}:
    """Compute top-K cosine similarity between job ads and O*NET occupations."""
    from pathlib import Path
    
    import numpy as np
    import pandas as pd
    
    from ai_index.const import pipeline_store_path
    from ai_index.utils import cosine_topk
    
    run_name = ctx.vars["run_name"]
    topk = int(ctx.vars["topk"])
    cosine_mode = ctx.vars["cosine_mode"]
    
    store_dir = pipeline_store_path / run_name / ctx.node_name
    # Load O*NET embeddings
    onet_data = np.load(onet_embed_meta["store_path"])
    onet_role = onet_data["role_embeddings"].astype(np.float32)
    onet_task = onet_data["task_embeddings"].astype(np.float32)
    onet_soc_codes = onet_embed_meta["soc_codes"]
    onet_titles = onet_embed_meta["titles"]
    
    print(f"compute_cosine_similarities: loaded O*NET embeddings: {onet_role.shape}")
    def _merge_topk(role_indices, role_scores, task_indices, task_scores, k, soc_codes, titles):
        """Merge role and task top-K results for a batch of job ads.
    
        For occupations appearing in both lists, average scores.
        Returns top-10 candidates per job ad.
        """
        n = len(role_indices)
        results = []
        for i in range(n):
            combo = {}
            for j in range(k):
                idx = int(role_indices[i, j])
                combo.setdefault(idx, []).append(float(role_scores[i, j]))
            for j in range(k):
                idx = int(task_indices[i, j])
                combo.setdefault(idx, []).append(float(task_scores[i, j]))
    
            # Average and sort
            candidates = sorted(
                ((idx, sum(scores) / len(scores)) for idx, scores in combo.items()),
                key=lambda x: x[1],
                reverse=True,
            )[:10]
    
            results.append([
                (soc_codes[idx], titles[idx], score)
                for idx, score in candidates
            ])
        return results
    month_metas = []
    
    for month_info in job_embed_meta["months"]:
        year = month_info["year"]
        filename = month_info["filename"]
        embed_path = Path(month_info["embed_path"])
        expected_count = month_info["row_count"]
    
        out_dir = store_dir / year
        out_path = out_dir / filename.replace(".npz", ".parquet")
    
        # Check cache
        if out_path.exists():
            existing = pd.read_parquet(out_path, columns=["job_id"])
            if len(existing) >= expected_count:
                print(f"compute_cosine_similarities: {year}/{filename} — {len(existing)} cached, skipping")
                month_metas.append({
                    "year": year,
                    "filename": filename,
                    "path": str(out_path),
                    "row_count": len(existing),
                })
                continue
    
        # Load job embeddings
        job_data = np.load(embed_path, allow_pickle=True)
        job_ids = job_data["job_ids"]
        job_role = job_data["role_embeddings"].astype(np.float32)
        job_task = job_data["task_embeddings"].astype(np.float32)
    
        print(f"compute_cosine_similarities: {year}/{filename} — computing top-{topk} for {len(job_ids)} ads (mode={cosine_mode})")
    
        role_result = cosine_topk(job_role, onet_role, topk, mode=cosine_mode)
        task_result = cosine_topk(job_task, onet_task, topk, mode=cosine_mode)
    
        all_results = _merge_topk(
            role_result["indices"], role_result["scores"],
            task_result["indices"], task_result["scores"],
            topk, onet_soc_codes, onet_titles,
        )
    
        # Build output DataFrame
        rows = []
        for job_id, candidates in zip(job_ids, all_results):
            soc_codes_list = [c[0] for c in candidates]
            titles_list = [c[1] for c in candidates]
            scores_list = [c[2] for c in candidates]
            rows.append({
                "job_id": str(job_id),
                "candidate_soc_codes": soc_codes_list,
                "candidate_titles": titles_list,
                "candidate_scores": scores_list,
            })
    
        df_out = pd.DataFrame(rows)
        out_dir.mkdir(parents=True, exist_ok=True)
        df_out.to_parquet(out_path, compression="snappy")
        print(f"compute_cosine_similarities: {year}/{filename} — saved {len(df_out)} results")
    
        month_metas.append({
            "year": year,
            "filename": filename,
            "path": str(out_path),
            "row_count": len(df_out),
        })
    
    total = sum(m["row_count"] for m in month_metas)
    print(f"compute_cosine_similarities: {total} total ads matched across {len(month_metas)} months")
    candidates_meta = {
        "months": month_metas,
        "topk": topk,
        "total_ads": total,
    }
    
    return {"candidates_meta": candidates_meta}
