# AUTOGENERATED! DO NOT EDIT!

async def main(ctx, print, ad_ids: list[int], onet_done: bool) -> {
    'ad_ids': list[int]
}:
    """Cosine similarity top-N candidates for reranking."""
    import json
    
    import duckdb
    import numpy as np
    import pandas as pd
    
    from ai_index import const
    run_name = ctx.vars["run_name"]
    cosine_topk = ctx.vars["cosine_topk"]
    
    output_dir = const.pipeline_store_path / run_name / "cosine_candidates"
    output_dir.mkdir(parents=True, exist_ok=True)
    onet_dir = const.pipeline_store_path / run_name / "embed_onet"
    
    with open(onet_dir / "onet_codes.json") as f:
        onet_codes = json.load(f)
    
    onet_embeds = np.load(onet_dir / "onet_embeddings.npy")
    
    # Load O*NET titles for output (from the source parquet)
    onet_targets = pd.read_parquet(const.onet_targets_path)
    onet_titles = dict(zip(onet_targets["O*NET-SOC Code"], onet_targets["Title"]))
    
    n_onet = len(onet_codes)
    print(f"cosine_candidates: loaded {n_onet} O*NET embeddings ({onet_embeds.shape})")
    
    # Normalize O*NET embeddings once
    onet_norms = np.linalg.norm(onet_embeds, axis=1, keepdims=True)
    onet_norms = np.maximum(onet_norms, 1e-10)
    onet_normed = onet_embeds / onet_norms
    embed_db = const.pipeline_store_path / run_name / "embed_ads" / "embeddings.duckdb"
    embed_conn = duckdb.connect(str(embed_db), read_only=True)
    
    n_ads = len(ad_ids)
    CHUNK_SIZE = 10000
    n_chunks = (n_ads + CHUNK_SIZE - 1) // CHUNK_SIZE
    print(f"cosine_candidates: {n_ads} ads x {n_onet} occupations, topk={cosine_topk}")
    print(f"  processing in {n_chunks} chunks")
    
    all_rows = []
    
    for chunk_idx in range(n_chunks):
        start = chunk_idx * CHUNK_SIZE
        end = min(start + CHUNK_SIZE, n_ads)
        chunk_ad_ids = ad_ids[start:end]
    
        # Load embeddings for this chunk
        embed_conn.execute("CREATE OR REPLACE TEMP TABLE _chunk_order (id BIGINT, pos INTEGER)")
        embed_conn.executemany(
            "INSERT INTO _chunk_order VALUES (?, ?)",
            [(int(aid), i) for i, aid in enumerate(chunk_ad_ids)],
        )
        rows = embed_conn.execute(
            "SELECT r.embedding FROM results r "
            "JOIN _chunk_order a ON r.id = a.id ORDER BY a.pos"
        ).fetchall()
    
        ad_embeds = np.stack([np.frombuffer(r[0], dtype=np.float32) for r in rows])
    
        # Normalize ad embeddings
        ad_norms = np.linalg.norm(ad_embeds, axis=1, keepdims=True)
        ad_norms = np.maximum(ad_norms, 1e-10)
        ad_normed = ad_embeds / ad_norms
    
        # Cosine similarity: (chunk_size, n_onet)
        sim_matrix = ad_normed @ onet_normed.T
    
        # Top-K per ad
        topk_clamped = min(cosine_topk, n_onet)
        top_indices = np.argsort(-sim_matrix, axis=1)[:, :topk_clamped]
        top_scores = np.take_along_axis(sim_matrix, top_indices, axis=1)
    
        for i in range(len(chunk_ad_ids)):
            for rank in range(topk_clamped):
                onet_idx = int(top_indices[i, rank])
                all_rows.append({
                    "ad_id": int(chunk_ad_ids[i]),
                    "rank": rank,
                    "onet_code": onet_codes[onet_idx],
                    "onet_title": onet_titles[onet_codes[onet_idx]],
                    "cosine_score": float(top_scores[i, rank]),
                })
    
        print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(chunk_ad_ids)} ads")
    
    embed_conn.close()
    candidates_df = pd.DataFrame(all_rows)
    output_path = output_dir / "candidates.parquet"
    candidates_df.to_parquet(output_path, index=False)
    
    print(f"cosine_candidates: wrote {len(candidates_df)} candidate rows ({n_ads} ads x topk={cosine_topk})")
    print(f"  output: {output_path}")
    if len(candidates_df) > 0:
        print(f"  score range: {candidates_df['cosine_score'].min():.4f} - {candidates_df['cosine_score'].max():.4f}")
    
    return ad_ids
