# AUTOGENERATED! DO NOT EDIT!

def embed_job_ads(job_ads, print) -> {"job_ad_embeddings": dict}:
    """Embed job ads with BGE-large."""
    print("embed_job_ads: returning dummy data")
    return {"job_ad_embeddings": {"dummy": True}}
