# AUTOGENERATED! DO NOT EDIT!

async def main(ctx, print) -> bool:
    """Embed O*NET occupations as single rich documents."""
    import json
    import time
    
    import numpy as np
    import pandas as pd
    
    from ai_index import const
    from ai_index.utils import aembed
    from ai_index.utils._model_config import _load_model_config
    run_name = ctx.vars["run_name"]
    embedding_model = ctx.vars["embedding_model"]
    sbatch_cache = ctx.vars["sbatch_cache"]
    sbatch_time = ctx.vars["sbatch_time"]
    
    output_dir = const.pipeline_store_path / run_name / "embed_onet"
    output_dir.mkdir(parents=True, exist_ok=True)
    expected_files = [
        output_dir / "onet_codes.json",
        output_dir / "onet_embeddings.npy",
    ]
    
    if all(f.exists() for f in expected_files):
        print(f"embed_onet: all output files exist in {const.rel(output_dir)}, skipping embedding")
        return True
    _, model_cfg = _load_model_config(const.embed_models_config_path, embedding_model)
    document_prefix = model_cfg.get("document_prefix", "")
    document_prompt_name = model_cfg.get("document_prompt_name", None)
    
    embed_prompt_kwargs = {}
    if document_prompt_name:
        embed_prompt_kwargs["prompt_name"] = document_prompt_name
        print(f"embed_onet: using named prompt: {document_prompt_name}")
    
    if document_prefix:
        print(f"embed_onet: applying document prefix: {document_prefix!r}")
    onet_targets = pd.read_parquet(const.onet_targets_path)
    print(f"embed_onet: loaded {len(onet_targets)} occupations from {const.rel(const.onet_targets_path)}")
    
    onet_codes = onet_targets["O*NET-SOC Code"].tolist()
    
    # Build a single rich text per occupation
    onet_texts = []
    for _, row in onet_targets.iterrows():
        text = f"{row['Title']}\n\n{row['Description']}\n\nKey tasks and skills: {row['Work Activities/Tasks/Skills']}"
        onet_texts.append(document_prefix + text)
    
    print(f"  Built {len(onet_texts)} texts")
    print(f"  Mean length: {np.mean([len(t) for t in onet_texts]):.0f} chars")
    print(f"  Sample: {onet_texts[0][:120]}...")
    started_at = time.time()
    slurm_jobs = []
    
    _sa = {}
    onet_embeddings = await aembed(
        onet_texts, model=embedding_model,
        cache=sbatch_cache, time=sbatch_time,
        slurm_accounting=_sa,
        **embed_prompt_kwargs,
    )
    if _sa:
        slurm_jobs.append(_sa)
    print(f"embed_onet: embeddings shape: {onet_embeddings.shape}")
    
    ended_at = time.time()
    np.save(output_dir / "onet_embeddings.npy", onet_embeddings.astype(np.float32))
    
    with open(output_dir / "onet_codes.json", "w") as f:
        json.dump(onet_codes, f)
    
    print(f"embed_onet: wrote {const.rel(output_dir)}")
    print(f"  onet_codes: {len(onet_codes)} codes")
    print(f"  onet_embeddings: {onet_embeddings.shape}")
    
    embed_meta = {
        "n_occupations": len(onet_targets),
        "embedding_dim": int(onet_embeddings.shape[1]),
        "started_at": started_at,
        "ended_at": ended_at,
        "elapsed_seconds": ended_at - started_at,
        "slurm_jobs": slurm_jobs,
        "slurm_total_seconds": sum(j.get("elapsed_seconds", 0) for j in slurm_jobs),
    }
    meta_path = output_dir / "embed_meta.json"
    with open(meta_path, "w") as f:
        json.dump(embed_meta, f, indent=2)
    print(f"embed_onet: wrote {const.rel(meta_path)}")
    
    return True
