# AUTOGENERATED! DO NOT EDIT!

def embed_onet(descriptions, print) -> {"onet_embeddings": dict}:
    """Embed O*NET occupations with BGE-large."""
    raise NotImplementedError("embed_onet not yet implemented")
