# AUTOGENERATED! DO NOT EDIT!

def fetch_onet(print) -> {"onet_tables": dict}:
    """Download and extract O*NET 30.0 database."""
    print("fetch_onet: returning dummy data")
    return {"onet_tables": {"dummy": True}}
