# AUTOGENERATED! DO NOT EDIT!

from typing import List

import numpy as np
from pydantic import BaseModel

class JobInfoModel(BaseModel):
    short_description: str
    tasks: List[str]
    skills: List[str]
    domain: str
    level: str

async def main(ctx, print, ad_ids: np.ndarray) -> {
    'successful_ad_ids': list[int]
}:
    """Run LLM to extract structured summaries from job ads."""
    import json
    
    import pandas as pd
    
    from ai_index import const
    from ai_index.utils import ResultStore, run_batched, strict_format, load_prompt, allm_generate, get_adzuna_conn, get_all_ad_ids
    def _validate_response(raw: str) -> str | None:
        """Validate an LLM response against JobInfoModel.
    
        Returns None if valid, or an error string.
        """
        try:
            JobInfoModel.model_validate_json(raw)
            return None
        except Exception as e:
            return f"{type(e).__name__}: {e}"
    run_name = ctx.vars["run_name"]
    llm_model = ctx.vars["llm_model"]
    sbatch_cache = ctx.vars["sbatch_cache"]
    sbatch_time = ctx.vars["sbatch_time"]
    batch_size = ctx.vars["llm_batch_size"]
    max_new_tokens = ctx.vars["llm_max_new_tokens"]
    temperature = ctx.vars["temperature"]
    top_p = ctx.vars["top_p"]
    top_k = ctx.vars["top_k"]
    resume = ctx.vars["summarise_resume"]
    max_retries = ctx.vars["summarise_max_retries"]
    raise_on_failure = ctx.vars["summarise_raise_on_failure"]
    max_concurrent = ctx.vars["llm_max_concurrent_batches"]
    duckdb_memory_limit = ctx.vars["duckdb_memory_limit"]
    
    SYSTEM_PROMPT = load_prompt(ctx.vars["system_prompt"])
    USER_PROMPT_TEMPLATE = load_prompt(ctx.vars["user_prompt"])
    
    output_dir = const.pipeline_store_path / run_name / "llm_summarise"
    output_dir.mkdir(parents=True, exist_ok=True)
    db_path = output_dir / "summaries.duckdb"
    json_schema = JobInfoModel.model_json_schema()
    _slurm_jobs = []
    
    async def _work_fn(chunk_ids):
        """Fetch ads, build prompts, call LLM, validate, return DataFrame."""
        ads_conn = get_adzuna_conn(read_only=True, memory_limit=duckdb_memory_limit)
        try:
            ads_conn.execute("CREATE OR REPLACE TEMP TABLE _chunk_ids (id BIGINT)")
            ads_conn.executemany("INSERT INTO _chunk_ids VALUES (?)", [(i,) for i in chunk_ids])
            ad_table = ads_conn.execute(
                "SELECT a.id, a.title, a.category_name, a.description "
                "FROM ads a JOIN _chunk_ids c ON a.id = c.id"
            ).fetch_arrow_table()
        finally:
            ads_conn.close()
    
        prompts = []
        ids_ordered = ad_table.column("id").to_pylist()
        for i in range(ad_table.num_rows):
            title = ad_table.column("title")[i].as_py()
            category = ad_table.column("category_name")[i].as_py()
            description = ad_table.column("description")[i].as_py()
            job_text = f"{title or ''}\n{category or ''}\n\n{(description or '')[:1200]}"
            prompts.append(strict_format(USER_PROMPT_TEMPLATE, job_text=job_text))
    
        _sa = {}
        responses = await allm_generate(
            prompts,
            model=llm_model,
            system_message=SYSTEM_PROMPT,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            json_schema=json_schema,
            cache=sbatch_cache,
            time=sbatch_time,
            slurm_accounting=_sa,
        )
        if _sa: _slurm_jobs.append(_sa)
    
        records = []
        for ad_id, response in zip(ids_ordered, responses):
            error = _validate_response(response)
            records.append({"id": ad_id, "data": response, "error": error})
        return pd.DataFrame(records)
    
    all_ids = ad_ids.tolist() if ad_ids is not None else get_all_ad_ids()
    
    store = ResultStore(db_path, {
        "id": "BIGINT NOT NULL",
        "data": "VARCHAR NOT NULL",
        "error": "VARCHAR",
    }, memory_limit=duckdb_memory_limit)
    
    summary_meta = await run_batched(
        all_ids, store, _work_fn,
        batch_size=batch_size,
        max_concurrent=max_concurrent,
        max_retries=max_retries,
        resume=resume,
        node_name="llm_summarise",
        print_fn=print,
        raise_on_failure=raise_on_failure,
    )
    store.close()
    del store
    summary_meta["slurm_jobs"] = _slurm_jobs
    summary_meta["slurm_total_seconds"] = sum(j.get("elapsed_seconds", 0) for j in _slurm_jobs)
    print(f"llm_summarise: wrote {const.rel(db_path)}")
    
    meta_path = output_dir / "summary_meta.json"
    with open(meta_path, "w") as f:
        json.dump(summary_meta, f, indent=2)
    print(f"llm_summarise: wrote {const.rel(meta_path)}")
    failed_set = set(summary_meta["failed_ids"])
    successful_ad_ids = [i for i in all_ids if i not in failed_set]
    return successful_ad_ids;
