# AUTOGENERATED! DO NOT EDIT!

import numpy as np

def main(ctx, print, ad_ids: np.ndarray) -> {
    'summary_meta': dict
}:
    """Run LLM to extract structured summaries from job ads."""
    import json
    import re
    from typing import List
    
    from pydantic import BaseModel, ValidationError
    
    from ai_index import const
    from ai_index.utils import get_ads_by_id, get_adzuna_conn, llm_generate
    class JobInfoModel(BaseModel):
        short_description: str
        tasks: List[str]
        skills: List[str]
        domain: str
        level: str
        automation_prof_score: int
    SYSTEM_PROMPT = (
        "You are a human resources highly-accurate data extraction bot. "
        "Extract the following details from the job advertisement provided by the user. "
        "You MUST NOT include more than 5 tasks or 5 skills. Stop the list at 5. Do not write more. "
        "Your response MUST be a single, valid JSON object (no markdown, no explanation, no code block). "
        "The JSON must have exactly these keys: "
        "'short_description', 'tasks', 'skills', 'domain', 'level', 'automation_prof_score'. "
        "- 'level': classify as 'Entry-Level' if the job requires <3 years experience or mentions 'junior'/'entry'; otherwise 'Experienced'. "
        "- 'automation_prof_score': integer 0-10 estimating AI automation risk. "
        "0 = AI-proof (requires physical/manual presence, creativity, leadership, or deep social judgment). "
        "10 = highly automatable by AI (routine, repetitive non-manual tasks like data entry, scheduling). "
        "Manual labour (e.g. cleaning, lifting, warehouse, driving) should usually score 0-3, "
        "since AI alone cannot replace them."
    )
    
    USER_TEMPLATE = """Extract:
    1. Short job description
    2. Bullet list of up to 5 key tasks
    3. Bullet list of up to 5 key skills
    4. The domain or industry
    5. The level (Entry-Level if <3 years experience or junior, else Experienced)
    6. Automation proof score (0=AI proof, 10=highly automatable non-manual tasks)
    
    Job Ad:
    {job_text}
    """
    _JSON_RE = re.compile(r"\{[\s\S]*\}", flags=re.DOTALL)
    
    
    def _parse_llm_output(raw: str) -> tuple[dict | None, str | None]:
        """Parse LLM output into a validated JobInfoModel dict.
    
        Returns (parsed_dict, error_string). Exactly one is None.
        """
        try:
            cleaned = re.sub(r"```json|```", "", raw).strip()
            m = _JSON_RE.search(cleaned)
            if not m:
                return None, "No JSON object found in LLM output"
            obj = json.loads(m.group(0))
            obj["tasks"] = (obj.get("tasks") or [])[:5]
            obj["skills"] = (obj.get("skills") or [])[:5]
            validated = JobInfoModel.model_validate(obj)
            return validated.model_dump(), None
        except (json.JSONDecodeError, ValidationError, Exception) as e:
            return None, f"{type(e).__name__}: {e}"
    if ad_ids is not None:
        ad_table = get_ads_by_id(
            ad_ids.tolist(),
            columns=["id", "title", "category_name", "description"],
        )
    else:
        conn = get_adzuna_conn(read_only=True)
        ad_table = conn.execute(
            "SELECT id, title, category_name, description FROM ads"
        ).fetch_arrow_table()
        conn.close()
    
    n_ads = len(ad_table)
    print(f"llm_summarise: processing {n_ads} ads")
    ids = ad_table.column("id").to_pylist()
    titles = ad_table.column("title").to_pylist()
    categories = ad_table.column("category_name").to_pylist()
    descriptions = ad_table.column("description").to_pylist()
    
    prompts = []
    for title, category, description in zip(titles, categories, descriptions):
        job_text = f"{title or ''}\n{category or ''}\n\n{(description or '')[:1200]}"
        prompts.append(USER_TEMPLATE.format(job_text=job_text))
    llm_model = ctx.vars["llm_model"]
    print(f"llm_summarise: calling llm_generate with model={llm_model!r} for {len(prompts)} prompts")
    
    responses = llm_generate(
        prompts,
        model=llm_model,
        system_message=SYSTEM_PROMPT,
        max_new_tokens=220,
    )
    import pandas as pd
    
    records = []
    n_success = 0
    n_failed = 0
    
    for ad_id, raw_response in zip(ids, responses):
        parsed, error = _parse_llm_output(raw_response)
        record = {
            "id": ad_id,
            "llm_output": raw_response,
            "error": error,
        }
        if parsed:
            record.update({
                "short_description": parsed["short_description"],
                "tasks": json.dumps(parsed["tasks"]),
                "skills": json.dumps(parsed["skills"]),
                "domain": parsed["domain"],
                "level": parsed["level"],
                "automation_prof_score": parsed["automation_prof_score"],
            })
            n_success += 1
        else:
            record.update({
                "short_description": None,
                "tasks": None,
                "skills": None,
                "domain": None,
                "level": None,
                "automation_prof_score": None,
            })
            n_failed += 1
        records.append(record)
    
    df = pd.DataFrame(records)
    
    run_name = ctx.vars["run_name"]
    output_dir = const.pipeline_store_path / run_name
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "summaries.parquet"
    df.to_parquet(output_path, index=False)
    
    print(f"llm_summarise: {n_success} succeeded, {n_failed} failed out of {n_ads}")
    print(f"llm_summarise: wrote {output_path}")
    
    summary_meta = {
        "parquet_path": str(output_path),
        "n_total": n_ads,
        "n_success": n_success,
        "n_failed": n_failed,
    }
    return summary_meta
