# AUTOGENERATED! DO NOT EDIT!

def main(ctx, print):
    """Filter O*NET occupations and build text descriptions for embedding."""
    import pandas as pd
    
    from ai_index import const
    PUBLIC_SECTOR_TITLES = [
        # Justice / Courts (8)
        "Judges, Magistrate Judges, and Magistrates",
        "Administrative Law Judges, Adjudicators, and Hearing Officers",
        "Judicial Law Clerks",
        "Coroners",
        "Bailiffs",
        "Probation Officers and Correctional Treatment Specialists",
        "Court, Municipal, and License Clerks",
        "Tax Examiners and Collectors, and Revenue Agents",
        # Policing / Security (10)
        "First-Line Supervisors of Police and Detectives",
        "Detectives and Criminal Investigators",
        "Police Identification and Records Officers",
        "Intelligence Analysts",
        "Fish and Game Wardens",
        "Parking Enforcement Workers",
        "Police and Sheriff's Patrol Officers",
        "Customs and Border Protection Officers",
        "Transit and Railroad Police",
        "Transportation Security Screeners",
        # Fire / Emergency (6)
        "Emergency Management Directors",
        "First-Line Supervisors of Firefighting and Prevention Workers",
        "Firefighters",
        "Fire Inspectors and Investigators",
        "Forest Fire Inspectors and Prevention Specialists",
        "Public Safety Telecommunicators",
        # Corrections (2)
        "First-Line Supervisors of Correctional Officers",
        "Correctional Officers and Jailers",
        # Postal (4)
        "Postmasters and Mail Superintendents",
        "Postal Service Clerks",
        "Postal Service Mail Carriers",
        "Postal Service Mail Sorters, Processors, and Processing Machine Operators",
        # Government (1)
        "Eligibility Interviewers, Government Programs",
        # Inspection (1)
        "Government Property Inspectors and Investigators",
        # Infrastructure (1)
        "Air Traffic Controllers",
    ]
    exclude_public_sector = ctx.vars["onet_exclude_public_sector"]
    top_n = ctx.vars["onet_top_n"]
    extract_dir = const.onet_store_path / "db_30_0_text"
    
    def _load_onet_table(name):
        return pd.read_csv(extract_dir / f"{name}.txt", sep="\t", header=0, encoding="utf-8", dtype=str)
    
    occupation_data = _load_onet_table("Occupation Data")
    task_statements = _load_onet_table("Task Statements")
    skills = _load_onet_table("Skills")
    work_activities = _load_onet_table("Work Activities")
    def _top_items_by_importance(occ_df, detail_df, element_col, top_n):
        """Get top-N items per occupation ranked by Importance scale score."""
        merged = occ_df[["O*NET-SOC Code", "Title"]].merge(
            detail_df[["O*NET-SOC Code", element_col, "Scale ID", "Data Value"]],
            on="O*NET-SOC Code", how="left",
        )
        merged = merged[merged["Scale ID"] == "IM"].copy()
        merged["Data Value"] = pd.to_numeric(merged["Data Value"], errors="coerce")
        merged = merged.dropna(subset=["Data Value"])
    
        grouped = merged.groupby(["Title", element_col], as_index=False)["Data Value"].sum()
        top = (
            grouped.sort_values(["Title", "Data Value"], ascending=[True, False])
            .groupby("Title")
            .head(top_n)
        )
        return top.groupby("Title")[element_col].apply(list).reset_index()
    
    # Top tasks (ranked by skill importance as cross-reference — matches old pipeline)
    occ_tasks = occupation_data[["O*NET-SOC Code", "Title"]].merge(
        task_statements[["O*NET-SOC Code", "Task"]], on="O*NET-SOC Code", how="left",
    )
    occ_tasks_skills = occ_tasks.merge(
        skills[["O*NET-SOC Code", "Element Name", "Scale ID", "Data Value"]],
        on="O*NET-SOC Code", how="left",
    )
    occ_tasks_skills = occ_tasks_skills[occ_tasks_skills["Scale ID"] == "IM"].copy()
    occ_tasks_skills["Data Value"] = occ_tasks_skills["Data Value"].astype(float)
    task_scores = occ_tasks_skills.groupby(["Title", "Task"])["Data Value"].sum().reset_index()
    top_tasks = (
        task_scores.sort_values(["Title", "Data Value"], ascending=[True, False])
        .groupby("Title").head(top_n)
    )
    tasks_grouped = top_tasks.groupby("Title")["Task"].apply(list).reset_index()
    tasks_grouped.rename(columns={"Task": "Top_Tasks"}, inplace=True)
    
    # Top skills
    skills_grouped = _top_items_by_importance(occupation_data, skills, "Element Name", top_n)
    skills_grouped.rename(columns={"Element Name": "Top_Skills"}, inplace=True)
    
    # Top work activities
    activities_grouped = _top_items_by_importance(occupation_data, work_activities, "Element Name", top_n)
    activities_grouped.rename(columns={"Element Name": "Top_Activities"}, inplace=True)
    
    # Merge all
    merged = tasks_grouped.merge(activities_grouped, on="Title", how="outer")
    merged = merged.merge(skills_grouped, on="Title", how="outer")
    for col in ["Top_Tasks", "Top_Activities", "Top_Skills"]:
        merged[col] = merged[col].apply(lambda x: x if isinstance(x, list) else [])
    merged["All_Items"] = merged["Top_Tasks"] + merged["Top_Activities"] + merged["Top_Skills"]
    occ_df = occupation_data.copy()
    occ_df["All_Items"] = occ_df["Title"].map(merged.set_index("Title")["All_Items"].to_dict())
    occ_df = occ_df.dropna(subset=["All_Items"])
    
    onet_targets = occ_df[["O*NET-SOC Code", "Title", "Description"]].copy()
    onet_targets["Job Role Description"] = onet_targets["Title"] + " - " + onet_targets["Description"].astype(str)
    onet_targets["Work Activities/Tasks/Skills"] = (
        onet_targets["Title"] + " - "
        + occ_df["All_Items"].apply(lambda items: ", ".join(str(i) for i in items))
    )
    if exclude_public_sector:
        exclude_set = set(PUBLIC_SECTOR_TITLES)
        before = len(onet_targets)
        onet_targets = onet_targets[~onet_targets["Title"].str.strip().isin(exclude_set)].reset_index(drop=True)
        n_dropped = before - len(onet_targets)
        print(f"prepare_onet_targets: dropped {n_dropped} public-sector occupations ({before} → {len(onet_targets)})")
    
    print(f"prepare_onet_targets: {len(onet_targets)} occupations with text descriptions (top_n={top_n})")
    
    onet_targets.to_parquet(const.onet_targets_path, index=False)
    print(f"prepare_onet_targets: wrote {const.rel(const.onet_targets_path)}")
