# AUTOGENERATED! DO NOT EDIT!

async def main(ctx, print, ad_ids: list[int]) -> {
    'ad_ids': list[int]
}:
    """Score filtered candidates with a reranker to produce exposure weights."""
    import asyncio
    import json
    import tempfile
    import time
    
    import numpy as np
    import pandas as pd
    import pyarrow as pa
    import pyarrow.parquet as pq
    
    from ai_index import const
    from ai_index.utils import arerank_pairs
    from ai_index.utils.batch import _dispatch_wave
    from isambard_utils.orchestrate import StagedInput
    from isambard_utils.staging import astage_files
    run_name = ctx.vars["run_name"]
    rerank_model = ctx.vars["rerank_model"]
    sbatch_cache = ctx.vars["sbatch_cache"]
    sbatch_time = ctx.vars["sbatch_time"]
    chunk_size = ctx.vars["chunk_size"]
    max_concurrent_chunks = ctx.vars["max_concurrent_chunks"]
    
    output_dir = const.pipeline_store_path / run_name / "rerank_candidates"
    output_dir.mkdir(parents=True, exist_ok=True)
    filtered_path = const.pipeline_store_path / run_name / "llm_filter_candidates" / "filtered_matches.parquet"
    
    onet_targets = pd.read_parquet(const.onet_targets_path)
    onet_titles_lookup = dict(zip(onet_targets["O*NET-SOC Code"], onet_targets["Title"]))
    
    # Build rich document text per occupation for reranking
    def _build_onet_doc(row):
        parts = [row["Title"]]
        alt = row["Alternate_Titles"]
        if len(alt) > 0:
            parts.append("Also known as: " + ", ".join(alt[:10]))
        parts.append(row["Description"])
        tasks = row["Top_Tasks"]
        if len(tasks) > 0:
            parts.append("Key tasks: " + "; ".join(tasks[:5]))
        return "\n".join(parts)
    
    onet_docs = dict(zip(onet_targets["O*NET-SOC Code"], onet_targets.apply(_build_onet_doc, axis=1)))
    
    n_ads = len(ad_ids)
    print(f"rerank_candidates: {n_ads} ads")
    print(f"  rerank_model: {rerank_model}")
    print(f"  reading from: {const.rel(filtered_path)}")
    
    # Use the ad_texts.parquet already written by sample_ads (deterministic, ZSTD).
    # This avoids re-exporting 5M ads from DuckDB (30 min, 30GB RAM) and ensures
    # a stable content hash across pipeline restarts for Isambard cache hits.
    ad_texts_path = const.pipeline_store_path / run_name / "sample_ads" / "ad_texts.parquet"
    
    # Export onet_docs.json (onet_code -> doc_text)
    staging_dir = output_dir / "_staging"
    staging_dir.mkdir(parents=True, exist_ok=True)
    onet_docs_path = staging_dir / "onet_docs.json"
    with open(onet_docs_path, "w") as f:
        json.dump(onet_docs, f, sort_keys=True)
    
    # Stage all three files to Isambard
    print("rerank_candidates: staging files to Isambard...")
    staged_refs = await astage_files(
        {
            "filtered_matches": filtered_path,
            "ad_texts": ad_texts_path,
            "onet_docs": onet_docs_path,
        },
        print_fn=print,
    )
    print("rerank_candidates: staging complete")
    CHUNK_SIZE = chunk_size
    
    # Read candidate structure ONCE as a sorted pyarrow table (~500MB columnar)
    # instead of 38M Python dicts (~15GB). Build an offset index for O(1) lookups.
    import pyarrow.compute as pc
    
    print("rerank_candidates: reading candidate structure...")
    _all_matches = pq.read_table(
        filtered_path,
        columns=["ad_id", "onet_code", "onet_title"],
    )
    # Sort by ad_id so each ad's candidates are contiguous
    _sort_indices = pc.sort_indices(_all_matches, sort_keys=[("ad_id", "ascending")])
    candidates_table = _all_matches.take(_sort_indices)
    del _all_matches, _sort_indices
    
    # Build offset index: ad_id -> (start, end) row range in sorted table
    _ad_ids_arr = candidates_table.column("ad_id").to_numpy()
    candidates_index = {}
    _i = 0
    while _i < len(_ad_ids_arr):
        _aid = int(_ad_ids_arr[_i])
        _start = _i
        while _i < len(_ad_ids_arr) and _ad_ids_arr[_i] == _aid:
            _i += 1
        candidates_index[_aid] = (_start, _i)
    del _ad_ids_arr
    print(f"  {len(candidates_index)} ads with candidates, {len(candidates_table)} rows ({candidates_table.nbytes / 1e6:.0f} MB)")
    
    reranked_schema = pa.schema([
        ("ad_id", pa.int64()),
        ("rank", pa.int32()),
        ("onet_code", pa.string()),
        ("onet_title", pa.string()),
        ("rerank_score", pa.float32()),
    ])
    
    output_path = output_dir / "reranked_matches.parquet"
    writer = pq.ParquetWriter(output_path, reranked_schema)
    
    n_chunks = (n_ads + CHUNK_SIZE - 1) // CHUNK_SIZE
    total_scored = 0
    slurm_jobs = []
    started_at = time.time()
    
    async def _process_chunk(chunk_idx, chunk_ad_ids):
        ads_with_candidates = [aid for aid in chunk_ad_ids if aid in candidates_index]
        if not ads_with_candidates:
            print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(chunk_ad_ids)} ads (no candidates)")
            return []
    
        # Build a StagedInput: the resolver on Isambard will read the staged
        # parquets/JSON and build the (query, doc_texts) items for this chunk.
        staged_items = StagedInput(
            resolver="rerank_pairs_items",
            sources=staged_refs,
            params={"ad_ids": ads_with_candidates},
        )
    
        _sa = {}
        scores_per_ad = await arerank_pairs(
            staged_items,
            model=rerank_model,
            cache=sbatch_cache, time=sbatch_time,
            slurm_accounting=_sa,
        )
        if _sa:
            slurm_jobs.append(_sa)
    
        # Map scores back to candidates using the offset index into the Arrow table
        _codes = candidates_table.column("onet_code")
        _titles = candidates_table.column("onet_title")
        chunk_rows = []
        for i, ad_id in enumerate(ads_with_candidates):
            start, end = candidates_index[ad_id]
            ad_scores = scores_per_ad[i]
            for rank in range(end - start):
                chunk_rows.append({
                    "ad_id": ad_id,
                    "rank": rank,
                    "onet_code": _codes[start + rank].as_py(),
                    "onet_title": _titles[start + rank].as_py(),
                    "rerank_score": float(ad_scores[rank]),
                })
    
        print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(ads_with_candidates)} ads, {len(chunk_rows)} scored")
        return chunk_rows
    
    def _on_chunk_result(chunk_rows):
        nonlocal total_scored
        if chunk_rows:
            writer.write_table(pa.Table.from_pylist(chunk_rows, schema=reranked_schema))
            total_scored += len(chunk_rows)
    
    await _dispatch_wave(
        [(i, ad_ids[i * CHUNK_SIZE : min((i + 1) * CHUNK_SIZE, n_ads)]) for i in range(n_chunks)],
        _process_chunk,
        _on_chunk_result,
        max_concurrent=max_concurrent_chunks,
    )
    
    writer.close()
    
    ended_at = time.time()
    print(f"rerank_candidates: scored {total_scored} candidate rows for {n_ads} ads")
    print(f"  output: {output_path}")
    
    rerank_meta = {
        "n_total": n_ads,
        "n_scored": total_scored,
        "started_at": started_at,
        "ended_at": ended_at,
        "elapsed_seconds": ended_at - started_at,
        "slurm_jobs": slurm_jobs,
        "slurm_total_seconds": sum(j.get("elapsed_seconds", 0) for j in slurm_jobs),
    }
    meta_path = output_dir / "rerank_meta.json"
    with open(meta_path, "w") as f:
        json.dump(rerank_meta, f, indent=2)
    print(f"  meta: {const.rel(meta_path)}")
    
    return ad_ids
