# AUTOGENERATED! DO NOT EDIT!

async def main(ctx, print, ad_ids: list[int]) -> {
    'ad_ids': list[int]
}:
    """Score filtered candidates with a reranker to produce exposure weights."""
    import json
    import time
    
    import duckdb
    import numpy as np
    import pandas as pd
    import pyarrow as pa
    import pyarrow.parquet as pq
    
    from ai_index import const
    from ai_index.utils import arerank_pairs, get_ads_by_id
    run_name = ctx.vars["run_name"]
    rerank_model = ctx.vars["rerank_model"]
    sbatch_time = ctx.vars["sbatch_time"]
    
    output_dir = const.pipeline_store_path / run_name / "rerank_candidates"
    output_dir.mkdir(parents=True, exist_ok=True)
    filtered_path = const.pipeline_store_path / run_name / "llm_filter_candidates" / "filtered_matches.parquet"
    
    onet_targets = pd.read_parquet(const.onet_targets_path)
    onet_descs = dict(zip(onet_targets["O*NET-SOC Code"], onet_targets["Description"]))
    onet_titles_lookup = dict(zip(onet_targets["O*NET-SOC Code"], onet_targets["Title"]))
    
    matches_conn = duckdb.connect()  # in-memory, queries parquet directly
    
    n_ads = len(ad_ids)
    print(f"rerank_candidates: {n_ads} ads")
    print(f"  rerank_model: {rerank_model}")
    print(f"  reading from: {const.rel(filtered_path)}")
    CHUNK_SIZE = 500  # ads per reranker batch
    
    reranked_schema = pa.schema([
        ("ad_id", pa.int64()),
        ("rank", pa.int32()),
        ("onet_code", pa.string()),
        ("onet_title", pa.string()),
        ("rerank_score", pa.float32()),
    ])
    
    output_path = output_dir / "reranked_matches.parquet"
    writer = pq.ParquetWriter(output_path, reranked_schema)
    
    n_chunks = (n_ads + CHUNK_SIZE - 1) // CHUNK_SIZE
    total_scored = 0
    slurm_jobs = []
    started_at = time.time()
    
    for chunk_idx in range(n_chunks):
        chunk_start = chunk_idx * CHUNK_SIZE
        chunk_end = min(chunk_start + CHUNK_SIZE, n_ads)
        chunk_ad_ids = ad_ids[chunk_start:chunk_end]
    
        # Load filtered candidates for this chunk
        id_list = ",".join(str(int(i)) for i in chunk_ad_ids)
        chunk_matches = matches_conn.execute(
            f"SELECT ad_id, onet_code, onet_title, cosine_score "
            f"FROM read_parquet('{filtered_path}') "
            f"WHERE ad_id IN ({id_list}) ORDER BY ad_id, rank"
        ).fetchdf()
    
        if chunk_matches.empty:
            print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(chunk_ad_ids)} ads (no candidates)")
            continue
    
        # Group candidates by ad
        candidates_by_ad = {}
        for ad_id, group in chunk_matches.groupby("ad_id"):
            candidates_by_ad[int(ad_id)] = group.to_dict("records")
    
        # Build query texts
        ads_with_candidates = [aid for aid in chunk_ad_ids if aid in candidates_by_ad]
        if not ads_with_candidates:
            continue
        ads_table = get_ads_by_id(ads_with_candidates, columns=["title", "description"])
        ads_df = ads_table.to_pandas().set_index("id")
    
        # Build (query, documents) items for all ads in the chunk, then score
        # them in a single arerank_pairs call. This sends one sbatch job per
        # chunk (~500 ads) instead of one per ad.
        items = []
        for ad_id in ads_with_candidates:
            candidates = candidates_by_ad[ad_id]
            query = f"{ads_df.loc[ad_id, 'title']}. {str(ads_df.loc[ad_id, 'description'] or '')[:3000]}"
            doc_texts = [f"{onet_titles_lookup[c['onet_code']]}: {onet_descs[c['onet_code']][:300]}" for c in candidates]
            items.append((query, doc_texts))
    
        _sa = {}
        scores_per_ad = await arerank_pairs(
            items,
            model=rerank_model,
            time=sbatch_time,
            slurm_accounting=_sa,
        )
        if _sa:
            slurm_jobs.append(_sa)
    
        chunk_rows = []
        for i, ad_id in enumerate(ads_with_candidates):
            candidates = candidates_by_ad[ad_id]
            ad_scores = scores_per_ad[i]
            for rank, c in enumerate(candidates):
                chunk_rows.append({
                    "ad_id": ad_id,
                    "rank": rank,
                    "onet_code": c["onet_code"],
                    "onet_title": c["onet_title"],
                    "rerank_score": float(ad_scores[rank]),
                })
    
        if chunk_rows:
            writer.write_table(pa.Table.from_pylist(chunk_rows, schema=reranked_schema))
            total_scored += len(chunk_rows)
    
        print(f"  chunk {chunk_idx + 1}/{n_chunks}: {len(ads_with_candidates)} ads, {len(chunk_rows)} scored")
    
    writer.close()
    matches_conn.close()
    
    ended_at = time.time()
    print(f"rerank_candidates: scored {total_scored} candidate rows for {n_ads} ads")
    print(f"  output: {output_path}")
    
    rerank_meta = {
        "n_total": n_ads,
        "n_scored": total_scored,
        "started_at": started_at,
        "ended_at": ended_at,
        "elapsed_seconds": ended_at - started_at,
        "slurm_jobs": slurm_jobs,
        "slurm_total_seconds": sum(j.get("elapsed_seconds", 0) for j in slurm_jobs),
    }
    meta_path = output_dir / "rerank_meta.json"
    with open(meta_path, "w") as f:
        json.dump(rerank_meta, f, indent=2)
    print(f"  meta: {const.rel(meta_path)}")
    
    return ad_ids
