# AUTOGENERATED! DO NOT EDIT!

def score_task_exposure(tasks, print) -> {"task_scores": dict}:
    """Compute GPT task-level AI exposure scores, aggregated to SOC level."""
    print("score_task_exposure: returning dummy data")
    return {"task_scores": {"dummy": True}}
