# nblite configuration
export_pipeline = """
nbs -> lib
nbs -> pts

nbs_tests -> lib_tests
nbs_tests -> pts_tests

nbs_isambard -> lib_isambard
nbs_isambard -> pts_isambard
"""

[cl.nbs]
path = "nbs/ai_index"
format = "ipynb"

[cl.pts]
path = "pts/ai_index"
format = "percent"

[cl.lib]
path = "src/ai_index"
format = "module"


[cl.nbs_tests]
path = "nbs/tests"
format = "ipynb"

[cl.pts_tests]
path = "pts/tests"
format = "percent"

[cl.lib_tests]
path = "src/tests"
format = "module"


[cl.nbs_isambard]
path = "nbs/isambard_utils"
format = "ipynb"

[cl.pts_isambard]
path = "pts/isambard_utils"
format = "percent"

[cl.lib_isambard]
path = "src/isambard_utils"
format = "module"
