# nblite configuration
export_pipeline = """
nbs -> lib
nbs -> pts

nbs_tests -> lib_tests
nbs_tests -> pts_tests

nbs_isambard -> lib_isambard
nbs_isambard -> pts_isambard

nbs_dev -> lib_dev
nbs_dev -> pts_dev

nbs_examples -> pts_examples

nbs_runner -> lib_runner
nbs_runner -> pts_runner
"""

[cl.nbs]
path = "nbs/ai_index"
format = "ipynb"

[cl.pts]
path = "pts/ai_index"
format = "percent"

[cl.lib]
path = "src/ai_index"
format = "module"


[cl.nbs_tests]
path = "nbs/tests"
format = "ipynb"

[cl.pts_tests]
path = "pts/tests"
format = "percent"

[cl.lib_tests]
path = "src/tests"
format = "module"


[cl.nbs_isambard]
path = "nbs/isambard_utils"
format = "ipynb"

[cl.pts_isambard]
path = "pts/isambard_utils"
format = "percent"

[cl.lib_isambard]
path = "src/isambard_utils"
format = "module"



[cl.nbs_dev]
path = "nbs/dev_utils"
format = "ipynb"

[cl.pts_dev]
path = "pts/dev_utils"
format = "percent"

[cl.lib_dev]
path = "src/dev_utils"
format = "module"


[cl.nbs_examples]
path = "nbs/examples"
format = "ipynb"

[cl.pts_examples]
path = "pts/examples"
format = "percent"


[cl.nbs_runner]
path = "nbs/llm_runner"
format = "ipynb"

[cl.pts_runner]
path = "pts/llm_runner"
format = "percent"

[cl.lib_runner]
path = "src/llm_runner"
format = "module"
