# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/isambard_utils/slurm.ipynb

__all__ = ['SlurmJob', 'acancel', 'ajob_log', 'astatus', 'asubmit', 'await_job', 'cancel', 'job_log', 'status', 'submit', 'wait']

# %% nbs/isambard_utils/slurm.ipynb 2
import asyncio
import json
import re
import time
from dataclasses import dataclass, field
from typing import Callable
from .config import IsambardConfig
from .ssh import run as ssh_run, arun as async_ssh_run, _get_config, _run_sync

# %% nbs/isambard_utils/slurm.ipynb 3
@dataclass
class SlurmJob:
    """Represents a submitted Slurm job."""
    job_id: str
    array_task_ids: list[int] | None = None

# %% nbs/isambard_utils/slurm.ipynb 4
def _parse_array_spec(spec: str) -> list[int]:
    """Parse a Slurm array spec like '0-9' or '1,3,5' into a list of task IDs."""
    ids = []
    for part in spec.split(","):
        if "-" in part:
            parts = part.split("-")
            start, end = int(parts[0]), int(parts[1])
            step = int(parts[2]) if len(parts) > 2 else 1
            ids.extend(range(start, end + 1, step))
        else:
            ids.append(int(part))
    return ids

# %% nbs/isambard_utils/slurm.ipynb 5
async def asubmit(sbatch_script: str, *, config: IsambardConfig | None = None) -> SlurmJob:
    """Submit an SBATCH script and return the job (async).

    Uploads the script to a temp file on the remote, runs sbatch, and parses
    the job ID from stdout.

    Args:
        sbatch_script: Complete SBATCH script content as a string.
        config: Isambard configuration.
    """
    config = _get_config(config)
    scripts_dir = f"{config.project_dir}/.sbatch_scripts"
    await async_ssh_run(f"mkdir -p {scripts_dir}", config=config)

    # Upload script to remote temp file
    import hashlib
    script_hash = hashlib.md5(sbatch_script.encode()).hexdigest()[:8]
    remote_script = f"{scripts_dir}/job_{script_hash}.sh"

    from .transfer import aupload_bytes
    await aupload_bytes(sbatch_script.encode(), remote_script, config=config)

    # Submit via sbatch
    result = await async_ssh_run(f"sbatch {remote_script}", config=config)
    # Parse: "Submitted batch job 12345"
    match = re.search(r"Submitted batch job (\d+)", result.stdout)
    if not match:
        raise RuntimeError(f"Failed to parse sbatch output: {result.stdout}")

    job_id = match.group(1)

    # Check for array jobs
    array_ids = None
    if "--array" in sbatch_script:
        array_match = re.search(r"#SBATCH\s+--array=(\S+)", sbatch_script)
        if array_match:
            array_spec = array_match.group(1)
            array_ids = _parse_array_spec(array_spec)

    return SlurmJob(job_id=job_id, array_task_ids=array_ids)

# %% nbs/isambard_utils/slurm.ipynb 6
def submit(sbatch_script: str, *, config: IsambardConfig | None = None) -> SlurmJob:
    """Submit an SBATCH script and return the job.

    Uploads the script to a temp file on the remote, runs sbatch, and parses
    the job ID from stdout.

    Args:
        sbatch_script: Complete SBATCH script content as a string.
        config: Isambard configuration.
    """
    return _run_sync(asubmit(sbatch_script, config=config))

# %% nbs/isambard_utils/slurm.ipynb 7
async def astatus(job_id: str, *, config: IsambardConfig | None = None) -> dict:
    """Get job status via squeue (async).

    Returns a dict with job information, or empty dict if job is no longer in
    the queue (completed/failed).

    Args:
        job_id: Slurm job ID.
        config: Isambard configuration.
    """
    config = _get_config(config)
    result = await async_ssh_run(
        f"squeue --json -j {job_id}",
        config=config, check=False,
    )
    if result.returncode != 0:
        return {}
    try:
        data = json.loads(result.stdout)
        jobs = data.get("jobs", [])
        if not jobs:
            return {}
        job = jobs[0]
        state = job.get("job_state", "UNKNOWN")
        # squeue --json may return state as a list (e.g. ["RUNNING"])
        if isinstance(state, list):
            state = state[0] if state else "UNKNOWN"
        return {
            "job_id": str(job.get("job_id", job_id)),
            "state": state,
            "name": job.get("name", ""),
            "node": job.get("nodes", ""),
            "time": job.get("time", ""),
            "partition": job.get("partition", ""),
        }
    except (json.JSONDecodeError, KeyError, IndexError):
        return {}

# %% nbs/isambard_utils/slurm.ipynb 8
def status(job_id: str, *, config: IsambardConfig | None = None) -> dict:
    """Get job status via squeue.

    Returns a dict with job information, or empty dict if job is no longer in
    the queue (completed/failed).

    Args:
        job_id: Slurm job ID.
        config: Isambard configuration.
    """
    return _run_sync(astatus(job_id, config=config))

# %% nbs/isambard_utils/slurm.ipynb 9
async def _asacct_status(job_id: str, *, config: IsambardConfig | None = None) -> dict:
    """Get completed job status via sacct (async)."""
    config = _get_config(config)
    result = await async_ssh_run(
        f"sacct -j {job_id} --json",
        config=config, check=False,
    )
    if result.returncode != 0:
        return {"state": "UNKNOWN"}
    try:
        data = json.loads(result.stdout)
        jobs = data.get("jobs", [])
        if not jobs:
            return {"state": "UNKNOWN"}
        job = jobs[0]
        state = job.get("state", {})
        if isinstance(state, dict):
            state = state.get("current", ["UNKNOWN"])[0]
        return {
            "job_id": str(job.get("job_id", job_id)),
            "state": state,
            "exit_code": job.get("exit_code", {}).get("return_code", None),
        }
    except (json.JSONDecodeError, KeyError, IndexError):
        return {"state": "UNKNOWN"}

# %% nbs/isambard_utils/slurm.ipynb 10
def _sacct_status(job_id: str, *, config: IsambardConfig | None = None) -> dict:
    """Get completed job status via sacct."""
    return _run_sync(_asacct_status(job_id, config=config))

# %% nbs/isambard_utils/slurm.ipynb 11
async def await_job(job_id: str, *, config: IsambardConfig | None = None,
                    poll_interval: int = 15, timeout: int | None = None,
                    on_poll: Callable | None = None) -> dict:
    """Poll until a job completes, then return sacct summary (async).

    Args:
        job_id: Slurm job ID.
        config: Isambard configuration.
        poll_interval: Seconds between status checks.
        timeout: Maximum seconds to wait (None = no limit).
        on_poll: Optional callback receiving status dict each iteration.
    """
    config = _get_config(config)
    start = time.time()

    while True:
        if timeout and (time.time() - start) > timeout:
            raise TimeoutError(f"Job {job_id} did not complete within {timeout}s")

        job_status = await astatus(job_id, config=config)
        if on_poll:
            on_poll(job_status)

        if not job_status:
            # Job left the queue -- check sacct for final status
            return await _asacct_status(job_id, config=config)

        state = job_status.get("state", "")
        if state in ("COMPLETED", "FAILED", "CANCELLED", "TIMEOUT", "NODE_FAIL",
                      "OUT_OF_MEMORY", "PREEMPTED"):
            return await _asacct_status(job_id, config=config)

        await asyncio.sleep(poll_interval)

# %% nbs/isambard_utils/slurm.ipynb 12
def wait(job_id: str, *, config: IsambardConfig | None = None,
         poll_interval: int = 15, timeout: int | None = None,
         on_poll: Callable | None = None) -> dict:
    """Poll until a job completes, then return sacct summary.

    Args:
        job_id: Slurm job ID.
        config: Isambard configuration.
        poll_interval: Seconds between status checks.
        timeout: Maximum seconds to wait (None = no limit).
        on_poll: Optional callback receiving status dict each iteration.
    """
    return _run_sync(await_job(job_id, config=config, poll_interval=poll_interval,
                               timeout=timeout, on_poll=on_poll))

# %% nbs/isambard_utils/slurm.ipynb 13
async def acancel(job_id: str, *, config: IsambardConfig | None = None) -> None:
    """Cancel a running or pending job via scancel (async).

    Args:
        job_id: Slurm job ID to cancel.
        config: Isambard configuration.
    """
    config = _get_config(config)
    await async_ssh_run(f"scancel {job_id}", config=config)

# %% nbs/isambard_utils/slurm.ipynb 14
def cancel(job_id: str, *, config: IsambardConfig | None = None) -> None:
    """Cancel a running or pending job via scancel.

    Args:
        job_id: Slurm job ID to cancel.
        config: Isambard configuration.
    """
    _run_sync(acancel(job_id, config=config))

# %% nbs/isambard_utils/slurm.ipynb 15
async def ajob_log(job_id: str, *, config: IsambardConfig | None = None,
                   stream: str = "stdout", tail: int | None = None) -> str:
    """Read job stdout or stderr log file from Isambard (async).

    Args:
        job_id: Slurm job ID.
        config: Isambard configuration.
        stream: 'stdout' or 'stderr'.
        tail: If set, return only the last N lines.
    """
    config = _get_config(config)
    ext = "out" if stream == "stdout" else "err"
    pattern = f"{config.logs_dir}/*_{job_id}.{ext}"

    cat_cmd = f"cat {pattern}"
    if tail:
        cat_cmd = f"tail -n {tail} {pattern}"

    result = await async_ssh_run(cat_cmd, config=config, check=False)
    return result.stdout if result.returncode == 0 else ""

# %% nbs/isambard_utils/slurm.ipynb 16
def job_log(job_id: str, *, config: IsambardConfig | None = None,
            stream: str = "stdout", tail: int | None = None) -> str:
    """Read job stdout or stderr log file from Isambard.

    Args:
        job_id: Slurm job ID.
        config: Isambard configuration.
        stream: 'stdout' or 'stderr'.
        tail: If set, return only the last N lines.
    """
    return _run_sync(ajob_log(job_id, config=config, stream=stream, tail=tail))
