# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/isambard_utils/ssh.ipynb

__all__ = ['check_clifton_auth', 'check_connection', 'run']

# %% nbs/isambard_utils/ssh.ipynb 2
import subprocess
import shlex
from pathlib import Path
from .config import IsambardConfig

# %% nbs/isambard_utils/ssh.ipynb 3
def _get_config(config: IsambardConfig | None) -> IsambardConfig:
    """Get config from argument or environment."""
    if config is not None:
        return config
    return IsambardConfig.from_env()

# %% nbs/isambard_utils/ssh.ipynb 4
def _build_ssh_cmd(config: IsambardConfig) -> list[str]:
    """Build the base SSH command list."""
    cmd = ["ssh", "-o", "StrictHostKeyChecking=accept-new"]
    if config.ssh_user:
        cmd.extend(["-l", config.ssh_user])
    cmd.append(config.ssh_host)
    return cmd

# %% nbs/isambard_utils/ssh.ipynb 5
def run(cmd: str, *, config: IsambardConfig | None = None, timeout: int = 120,
        check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    """Run a command on the Isambard login node via SSH.

    Args:
        cmd: Shell command to execute remotely.
        config: Isambard configuration. Defaults to IsambardConfig.from_env().
        timeout: Timeout in seconds.
        check: Raise CalledProcessError on non-zero exit.
        capture: Capture stdout/stderr (True) or inherit terminal (False).
    """
    config = _get_config(config)
    ssh_cmd = _build_ssh_cmd(config) + [cmd]
    return subprocess.run(
        ssh_cmd,
        timeout=timeout,
        check=check,
        capture_output=capture,
        text=True,
    )

# %% nbs/isambard_utils/ssh.ipynb 6
def check_connection(config: IsambardConfig | None = None) -> bool:
    """Test SSH connectivity. Returns True if connection succeeds."""
    try:
        result = run("echo ok", config=config, timeout=30, check=False)
        return result.returncode == 0 and "ok" in result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False

# %% nbs/isambard_utils/ssh.ipynb 7
def check_clifton_auth() -> bool:
    """Check if Clifton certificate is still valid by looking for recent cert files."""
    cert_path = Path.home() / ".ssh" / "config_clifton"
    if not cert_path.exists():
        return False
    # If the config file exists, attempt a quick SSH connection test
    # The actual cert validity is handled by the SSH agent
    try:
        result = subprocess.run(
            ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10",
             "-F", str(cert_path), "a5u.aip2.isambard", "echo ok"],
            capture_output=True, text=True, timeout=15, check=False,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False
