# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/const.ipynb

__all__ = ['adulib_cache_path', 'assets_path', 'llm_models_config_path', 'pkg_path', 'store_path']

# %% nbs/ai_index/const.ipynb 2
from pathlib import Path

pkg_path = Path(__file__).resolve().parent
assets_path = pkg_path / "assets"
store_path = pkg_path / "store"
llm_models_config_path = assets_path / "llm_models.toml"
adulib_cache_path = store_path / "adulib_cache"
