# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/const.ipynb

__all__ = ['adulib_cache_path', 'adzuna_store_path', 'assets_path', 'embed_models_config_path', 'inputs_path', 'llm_models_config_path', 'onet_store_path', 'pkg_path', 'store_path']

# %% nbs/ai_index/const.ipynb 2
from importlib.resources import files
from pathlib import Path

pkg_path = Path(str(files("ai_index")))
assets_path = pkg_path / "assets"
store_path = pkg_path / "store"
inputs_path = store_path / "inputs"

llm_models_config_path = assets_path / "llm_models.toml"
embed_models_config_path = assets_path / "embed_models.toml"
adulib_cache_path = store_path / "adulib_cache"

onet_store_path = inputs_path / "onet"
adzuna_store_path = inputs_path / "adzuna"
