# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/run_pipeline.ipynb

__all__ = ['main', 'run_pipeline_async']

# %% nbs/ai_index/run_pipeline.ipynb 2
import asyncio
from importlib import resources
from pathlib import Path
from netrun.core import Net, NetConfig

# %% nbs/ai_index/run_pipeline.ipynb 3
async def run_pipeline_async():
    """Load and run the full pipeline, returning output queue results."""
    config_path = resources.files("ai_index.assets") / "netrun.json"
    config = NetConfig.from_file(str(config_path))
    config.project_root_override = str(Path.cwd())

    async with Net(config) as net:
        made_progress = True
        while made_progress:
            made_progress, _ = await net.run_until_blocked()

        results = net.flush_all_output_queues()
        for queue_name, outputs in results.items():
            print(f"\n=== Output queue: {queue_name} ({len(outputs)} packet(s)) ===")
            for i, output in enumerate(outputs):
                print(f"  [{i}] {output}")

    return results

# %% nbs/ai_index/run_pipeline.ipynb 4
def main():
    """Sync entry point for the run-pipeline CLI command."""
    asyncio.run(run_pipeline_async())
