# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/utils.ipynb

__all__ = ['acosine_topk', 'aembed', 'allm_generate', 'build_insert_from_parquet', 'cosine_topk', 'embed', 'ensure_ads_table', 'get_ads_by_id', 'get_adzuna_conn', 'get_all_ad_ids', 'llm_generate']

# %% nbs/ai_index/utils.ipynb 2
import tomllib
from pathlib import Path
from .const import llm_models_config_path, embed_models_config_path, adulib_cache_path

from adulib.caching import set_default_cache_path
set_default_cache_path(adulib_cache_path)

# %% nbs/ai_index/utils.ipynb 3
def _load_model_config(config_path: Path, model_key: str) -> tuple[str, dict]:
    """Load config for a named model key.

    Looks up cfg["models"][model_key], reads its mode, merges
    cfg["defaults"][mode] with the model entry (minus 'mode' key).
    Returns (mode, merged_dict).
    """
    with open(config_path, "rb") as f:
        cfg = tomllib.load(f)
    models = cfg.get("models", {})
    if model_key not in models:
        available = ", ".join(sorted(models.keys()))
        raise ValueError(f"Unknown model key {model_key!r}. Available: {available}")
    entry = dict(models[model_key])
    mode = entry.pop("mode")
    defaults = dict(cfg.get("defaults", {}).get(mode, {}))
    defaults.update(entry)
    return mode, defaults

# %% nbs/ai_index/utils.ipynb 4
# Keys that belong to run_remote/arun_remote (orchestration), not to the
# underlying llm_runner operation. _split_remote_kwargs() pops these from the
# config dict so they're passed to run_remote, while the rest goes to the
# remote llm_runner CLI as config_dict.
_RUN_REMOTE_KEYS = {
    "setup", "job_name", "time", "transfer_modes",
    "output_transfer", "isambard_config", "print_fn",
}

def _resolve_model_args(config_path, model_key, kwargs):
    """Resolve config + kwargs into (mode, model_name, cfg) tuple."""
    mode, cfg = _load_model_config(config_path, model_key)
    cfg.update(kwargs)
    model_name = cfg.pop("model")
    return mode, model_name, cfg

def _split_remote_kwargs(cfg):
    """Pop run_remote keys from cfg and return them as a separate dict."""
    return {k: cfg.pop(k) for k in list(cfg) if k in _RUN_REMOTE_KEYS}

def llm_generate(
    prompts: list[str],
    *,
    model: str,
    **kwargs,
) -> list[str]:
    """Generate LLM responses using a named model key from llm_models.toml.

    The model key determines the execution mode (api/local/sbatch).
    Any explicit **kwargs override config values.
    """
    mode, model_name, cfg = _resolve_model_args(llm_models_config_path, model, kwargs)

    if mode in ("api", "local"):
        from llm_runner.llm import run_llm_generate
        if mode == "api":
            cfg["backend"] = "api"
        return run_llm_generate(prompts, model_name=model_name, **cfg)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import run_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model_name
        return run_remote(
            "llm_generate",
            inputs={"prompts": prompts},
            config_dict=cfg,
            required_models=[model_name],
            **remote_kw,
        )["responses"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 5
import asyncio

async def allm_generate(
    prompts: list[str],
    *,
    model: str,
    **kwargs,
) -> list[str]:
    """Async version of llm_generate.

    For api/local modes, runs the sync run_llm_generate in a thread.
    For sbatch mode, uses the native async arun_remote.
    """
    mode, model_name, cfg = _resolve_model_args(llm_models_config_path, model, kwargs)

    if mode in ("api", "local"):
        from llm_runner.llm import run_llm_generate
        if mode == "api":
            cfg["backend"] = "api"
        return await asyncio.to_thread(run_llm_generate, prompts, model_name=model_name, **cfg)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import arun_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model_name
        return (await arun_remote(
            "llm_generate",
            inputs={"prompts": prompts},
            config_dict=cfg,
            required_models=[model_name],
            **remote_kw,
        ))["responses"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 7
import numpy as np

def embed(
    texts: list[str],
    *,
    model: str,
    **kwargs,
) -> np.ndarray:
    """Embed texts using a named model key from embed_models.toml.

    The model key determines the execution mode (api/local/sbatch).
    Any explicit **kwargs override config values.

    Returns:
        numpy array of shape (len(texts), embedding_dim).
    """
    mode, model_name, cfg = _resolve_model_args(embed_models_config_path, model, kwargs)

    if mode == "local":
        from llm_runner.embed import run_embeddings
        return run_embeddings(texts, model_name=model_name, **cfg)

    elif mode == "api":
        from adulib.llm import batch_embeddings
        batch_size = cfg.pop("batch_size", 1000)
        embeddings, _ = batch_embeddings(model_name, input=texts, batch_size=batch_size, **cfg)
        return np.array(embeddings)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import run_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model_name
        return run_remote(
            "embed",
            inputs={"texts": texts},
            config_dict=cfg,
            required_models=[model_name],
            **remote_kw,
        )["embeddings"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 8
async def aembed(
    texts: list[str],
    *,
    model: str,
    **kwargs,
) -> np.ndarray:
    """Async version of embed.

    For local mode, runs run_embeddings in a thread.
    For api mode, uses adulib's native async_batch_embeddings.
    For sbatch mode, uses arun_remote.
    """
    mode, model_name, cfg = _resolve_model_args(embed_models_config_path, model, kwargs)

    if mode == "local":
        from llm_runner.embed import run_embeddings
        return await asyncio.to_thread(run_embeddings, texts, model_name=model_name, **cfg)

    elif mode == "api":
        from adulib.llm import async_batch_embeddings
        batch_size = cfg.pop("batch_size", 1000)
        embeddings, _ = await async_batch_embeddings(model_name, input=texts, batch_size=batch_size, **cfg)
        return np.array(embeddings)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import arun_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model_name
        return (await arun_remote(
            "embed",
            inputs={"texts": texts},
            config_dict=cfg,
            required_models=[model_name],
            **remote_kw,
        ))["embeddings"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 10
import duckdb
import pyarrow as pa

from .const import adzuna_db_path

# Canonical schema for the ads table. All string-like columns use VARCHAR.
# year/month are partition columns added during ingest.
_ADS_SCHEMA = [
    ("id", "BIGINT NOT NULL"),
    ("year", "INTEGER NOT NULL"),
    ("month", "INTEGER NOT NULL"),
    ("date_created", "VARCHAR"),
    ("title", "VARCHAR"),
    ("description", "VARCHAR"),
    ("location_raw", "VARCHAR"),
    ("geo_lat", "VARCHAR"),
    ("geo_lng", "VARCHAR"),
    ("LAD22CD", "VARCHAR"),
    ("LAD22NM", "VARCHAR"),
    ("LAD24CD", "VARCHAR"),
    ("category_id", "BIGINT"),
    ("category_name", "VARCHAR"),
    ("company_raw", "VARCHAR"),
    ("company_id", "DOUBLE"),
    ("normalised_company", "VARCHAR"),
    ("salary_min", "DOUBLE"),
    ("salary_max", "DOUBLE"),
    ("salary_currency", "VARCHAR"),
    ("salary_predicted", "DOUBLE"),
    ("salary_raw", "VARCHAR"),
    ("contract_type", "VARCHAR"),
    ("contract_time", "VARCHAR"),
    ("soc2020_major_group", "VARCHAR"),
    ("soc2020_submajor_group", "VARCHAR"),
    ("soc2020_minor_group", "VARCHAR"),
    ("soc2020", "VARCHAR"),
    ("sic_section", "VARCHAR"),
    ("SIC1", "VARCHAR"),
    ("SIC2", "VARCHAR"),
    ("SIC3", "VARCHAR"),
    ("SIC4", "VARCHAR"),
]

# Columns that may be numeric (double) in older parquets and need CAST to VARCHAR
_CAST_IF_NUMERIC = {
    "geo_lat", "geo_lng",
    "soc2020_major_group", "soc2020_submajor_group",
    "soc2020_minor_group", "soc2020",
}


def get_adzuna_conn(read_only: bool = False) -> duckdb.DuckDBPyConnection:
    """Open a DuckDB connection to the Adzuna database."""
    return duckdb.connect(str(adzuna_db_path), read_only=read_only)


def ensure_ads_table(conn: duckdb.DuckDBPyConnection) -> None:
    """Create the ads table and indexes if they don't exist."""
    cols = ", ".join(f"{name} {dtype}" for name, dtype in _ADS_SCHEMA)
    conn.execute(f"CREATE TABLE IF NOT EXISTS ads ({cols})")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_ads_id ON ads(id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_ads_year_month ON ads(year, month)")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS _meta (
            key VARCHAR PRIMARY KEY,
            value VARCHAR
        )
    """)


def build_insert_from_parquet(
    parquet_path: str,
    year: int,
    month: int,
    source_schema: list[str] | None = None,
) -> str:
    """Build an INSERT INTO ads SELECT ... FROM read_parquet(...) statement.

    Handles schema differences: casts numeric columns to VARCHAR,
    fills missing columns with NULL, and adds year/month.

    Args:
        parquet_path: Path to the parquet file.
        year: Year partition value.
        month: Month partition value.
        source_schema: Column names in the source parquet. If None,
            reads from the file metadata.
    """
    if source_schema is None:
        import pyarrow.parquet as pq
        source_schema_obj = pq.read_schema(parquet_path)
        source_cols = set(source_schema_obj.names)
        # Build a map of source column types for cast decisions
        source_types = {f.name: f.type for f in source_schema_obj}
    else:
        source_cols = set(source_schema)
        source_types = {}

    select_exprs = []
    for col_name, _ in _ADS_SCHEMA:
        if col_name == "year":
            select_exprs.append(f"{year} AS year")
        elif col_name == "month":
            select_exprs.append(f"{month} AS month")
        elif col_name not in source_cols:
            select_exprs.append(f"NULL AS {col_name}")
        elif col_name in _CAST_IF_NUMERIC and source_types:
            # Check if source type is numeric (double/float)
            src_type = source_types.get(col_name)
            if src_type is not None and (pa.types.is_floating(src_type) or pa.types.is_integer(src_type)):
                select_exprs.append(f"CAST({col_name} AS VARCHAR) AS {col_name}")
            else:
                select_exprs.append(col_name)
        else:
            select_exprs.append(col_name)

    select_clause = ", ".join(select_exprs)
    return f"INSERT INTO ads SELECT {select_clause} FROM read_parquet('{parquet_path}')"


def get_ads_by_id(
    ids: list[int],
    columns: list[str] | None = None,
) -> pa.Table:
    """Retrieve job ad rows by ID from the Adzuna DuckDB store.

    Args:
        ids: List of job ad IDs to retrieve.
        columns: Columns to include in the result. If None, all columns
            are returned. The ``id`` column is always included.

    Returns:
        A pyarrow Table with matching rows.
    """
    if columns is not None and "id" not in columns:
        columns = ["id"] + list(columns)

    col_clause = ", ".join(columns) if columns else "*"
    placeholders = ", ".join(["?"] * len(ids))

    conn = get_adzuna_conn(read_only=True)
    try:
        result = conn.execute(
            f"SELECT {col_clause} FROM ads WHERE id IN ({placeholders})", ids
        ).fetch_arrow_table()
    finally:
        conn.close()
    return result

def get_all_ad_ids():
    conn = get_adzuna_conn(read_only=True)
    all_ids = conn.execute("SELECT id FROM ads").fetchnumpy()["id"].tolist()
    conn.close()
    return all_ids

# %% nbs/ai_index/utils.ipynb 12
def cosine_topk(
    A: np.ndarray,
    B: np.ndarray,
    k: int = 5,
    *,
    mode: str = "local",
    **kwargs,
) -> dict:
    """Compute top-K cosine similarity (api/local/sbatch).

    Returns:
        Dict with "indices" (n, k) and "scores" (n, k) arrays.
    """
    if mode in ("api", "local"):
        from llm_runner.cosine import run_cosine_topk
        if mode == "api":
            kwargs.setdefault("device", "cpu")
        return run_cosine_topk(A, B, k, **kwargs)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import run_remote
        cfg = dict(kwargs)
        remote_kw = _split_remote_kwargs(cfg)
        remote_kw.setdefault("job_name", "cosine_topk")
        cfg["k"] = k
        return run_remote(
            "cosine_topk",
            inputs={"A": A, "B": B},
            config_dict=cfg,
            **remote_kw,
        )

    else:
        raise ValueError(f"Unknown mode: {mode!r}. cosine_topk supports 'local' and 'sbatch'.")

# %% nbs/ai_index/utils.ipynb 13
async def acosine_topk(
    A: np.ndarray,
    B: np.ndarray,
    k: int = 5,
    *,
    mode: str = "local",
    **kwargs,
) -> dict:
    """Async version of cosine_topk.

    For api/local mode, runs in a thread. For sbatch, uses arun_remote.
    """
    if mode in ("api", "local"):
        from llm_runner.cosine import run_cosine_topk
        if mode == "api":
            kwargs.setdefault("device", "cpu")
        return await asyncio.to_thread(run_cosine_topk, A, B, k, **kwargs)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import arun_remote
        cfg = dict(kwargs)
        remote_kw = _split_remote_kwargs(cfg)
        remote_kw.setdefault("job_name", "cosine_topk")
        cfg["k"] = k
        return await arun_remote(
            "cosine_topk",
            inputs={"A": A, "B": B},
            config_dict=cfg,
            **remote_kw,
        )

    else:
        raise ValueError(f"Unknown mode: {mode!r}. cosine_topk supports 'local' and 'sbatch'.")
