# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/utils.ipynb

__all__ = ['acosine_topk', 'aembed', 'allm_generate', 'cosine_topk', 'embed', 'llm_generate']

# %% nbs/ai_index/utils.ipynb 2
import tomllib
from pathlib import Path
from .const import llm_models_config_path, embed_models_config_path

# %% nbs/ai_index/utils.ipynb 3
def _load_model_config(config_path: Path, mode: str, model: str | None) -> dict:
    """Load config: {mode}.defaults -> {mode}."{model}" """
    with open(config_path, "rb") as f:
        cfg = tomllib.load(f)
    mode_cfg = cfg.get(mode, {})
    result = dict(mode_cfg.get("defaults", {}))
    if model and model in mode_cfg:
        result.update(mode_cfg[model])
    return result

# %% nbs/ai_index/utils.ipynb 4
# Keys that belong to run_remote/arun_remote (orchestration), not to the
# underlying llm_runner operation. _split_remote_kwargs() pops these from the
# config dict so they're passed to run_remote, while the rest goes to the
# remote llm_runner CLI as config_dict.
_RUN_REMOTE_KEYS = {
    "setup", "job_name", "time", "transfer_modes",
    "output_transfer", "isambard_config", "print_fn",
}

def _resolve_model_args(config_path, mode, model, kwargs):
    """Resolve config + kwargs into (model, cfg) tuple."""
    cfg = _load_model_config(config_path, mode, model)
    cfg.update(kwargs)
    if model is None:
        model = cfg.pop("model")
    else:
        cfg.pop("model", None)
    return model, cfg

def _split_remote_kwargs(cfg):
    """Pop run_remote keys from cfg and return them as a separate dict."""
    return {k: cfg.pop(k) for k in list(cfg) if k in _RUN_REMOTE_KEYS}

def llm_generate(
    prompts: list[str],
    *,
    mode: str = "api",
    model: str | None = None,
    **kwargs,
) -> list[str]:
    """Generate LLM responses using api, local, or sbatch mode.

    Config is loaded from llm_models.toml ({mode}.defaults -> {mode}."{model}"),
    then any explicit **kwargs override config values.
    """
    model, cfg = _resolve_model_args(llm_models_config_path, mode, model, kwargs)

    if mode in ("api", "local"):
        from llm_runner.llm import run_llm_generate
        if mode == "api":
            cfg["backend"] = "api"
        return run_llm_generate(prompts, model_name=model, **cfg)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import run_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model
        return run_remote(
            "llm_generate",
            inputs={"prompts": prompts},
            config_dict=cfg,
            required_models=[model],
            **remote_kw,
        )["responses"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 5
import asyncio

async def allm_generate(
    prompts: list[str],
    *,
    mode: str = "api",
    model: str | None = None,
    **kwargs,
) -> list[str]:
    """Async version of llm_generate.

    For api/local modes, runs the sync run_llm_generate in a thread.
    For sbatch mode, uses the native async arun_remote.
    """
    model, cfg = _resolve_model_args(llm_models_config_path, mode, model, kwargs)

    if mode in ("api", "local"):
        from llm_runner.llm import run_llm_generate
        if mode == "api":
            cfg["backend"] = "api"
        return await asyncio.to_thread(run_llm_generate, prompts, model_name=model, **cfg)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import arun_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model
        return (await arun_remote(
            "llm_generate",
            inputs={"prompts": prompts},
            config_dict=cfg,
            required_models=[model],
            **remote_kw,
        ))["responses"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 7
import numpy as np

def embed(
    texts: list[str],
    *,
    mode: str = "local",
    model: str | None = None,
    **kwargs,
) -> np.ndarray:
    """Embed texts using local SentenceTransformer, cloud API (adulib), or sbatch.

    Config is loaded from embed_models.toml ({mode}.defaults -> {mode}."{model}"),
    then any explicit **kwargs override config values.

    Returns:
        numpy array of shape (len(texts), embedding_dim).
    """
    model, cfg = _resolve_model_args(embed_models_config_path, mode, model, kwargs)

    if mode == "local":
        from llm_runner.embed import run_embeddings
        return run_embeddings(texts, model_name=model, **cfg)

    elif mode == "api":
        from adulib.llm import batch_embeddings
        batch_size = cfg.pop("batch_size", 1000)
        embeddings, _ = batch_embeddings(model, input=texts, batch_size=batch_size, **cfg)
        return np.array(embeddings)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import run_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model
        return run_remote(
            "embed",
            inputs={"texts": texts},
            config_dict=cfg,
            required_models=[model],
            **remote_kw,
        )["embeddings"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 8
async def aembed(
    texts: list[str],
    *,
    mode: str = "local",
    model: str | None = None,
    **kwargs,
) -> np.ndarray:
    """Async version of embed.

    For local mode, runs run_embeddings in a thread.
    For api mode, uses adulib's native async_batch_embeddings.
    For sbatch mode, uses arun_remote.
    """
    model, cfg = _resolve_model_args(embed_models_config_path, mode, model, kwargs)

    if mode == "local":
        from llm_runner.embed import run_embeddings
        return await asyncio.to_thread(run_embeddings, texts, model_name=model, **cfg)

    elif mode == "api":
        from adulib.llm import async_batch_embeddings
        batch_size = cfg.pop("batch_size", 1000)
        embeddings, _ = await async_batch_embeddings(model, input=texts, batch_size=batch_size, **cfg)
        return np.array(embeddings)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import arun_remote
        remote_kw = _split_remote_kwargs(cfg)
        cfg["model_name"] = model
        return (await arun_remote(
            "embed",
            inputs={"texts": texts},
            config_dict=cfg,
            required_models=[model],
            **remote_kw,
        ))["embeddings"]

    else:
        raise ValueError(f"Unknown mode: {mode!r}")

# %% nbs/ai_index/utils.ipynb 10
def cosine_topk(
    A: np.ndarray,
    B: np.ndarray,
    k: int = 5,
    *,
    mode: str = "local",
    **kwargs,
) -> dict:
    """Compute top-K cosine similarity (local or sbatch).

    Returns:
        Dict with "indices" (n, k) and "scores" (n, k) arrays.
    """
    if mode == "local":
        from llm_runner.cosine import run_cosine_topk
        return run_cosine_topk(A, B, k, **kwargs)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import run_remote
        cfg = dict(kwargs)
        remote_kw = _split_remote_kwargs(cfg)
        remote_kw.setdefault("job_name", "cosine_topk")
        cfg["k"] = k
        return run_remote(
            "cosine_topk",
            inputs={"A": A, "B": B},
            config_dict=cfg,
            **remote_kw,
        )

    else:
        raise ValueError(f"Unknown mode: {mode!r}. cosine_topk supports 'local' and 'sbatch'.")

# %% nbs/ai_index/utils.ipynb 11
async def acosine_topk(
    A: np.ndarray,
    B: np.ndarray,
    k: int = 5,
    *,
    mode: str = "local",
    **kwargs,
) -> dict:
    """Async version of cosine_topk.

    For local mode, runs in a thread. For sbatch, uses arun_remote.
    """
    if mode == "local":
        from llm_runner.cosine import run_cosine_topk
        return await asyncio.to_thread(run_cosine_topk, A, B, k, **kwargs)

    elif mode == "sbatch":
        from isambard_utils.orchestrate import arun_remote
        cfg = dict(kwargs)
        remote_kw = _split_remote_kwargs(cfg)
        remote_kw.setdefault("job_name", "cosine_topk")
        cfg["k"] = k
        return await arun_remote(
            "cosine_topk",
            inputs={"A": A, "B": B},
            config_dict=cfg,
            **remote_kw,
        )

    else:
        raise ValueError(f"Unknown mode: {mode!r}. cosine_topk supports 'local' and 'sbatch'.")
