# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/validation/__init__.ipynb

__all__ = ['run_validation', 'plan_runs', 'analyze', 'analyze_main']

# %% nbs/validation/__init__.ipynb 2
import sys

from .run_validation import run_validation
from .run_all import plan_runs
from .analyze import analyze

# %% nbs/validation/__init__.ipynb 3
def analyze_main():
    """CLI entry point for analyze-validation."""
    args = [a for a in sys.argv[1:] if not a.startswith("--")]

    if len(args) != 1:
        print(
            "Usage: uv run analyze-validation <run_def_name>",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        analyze(args[0])
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
