# AUTOGENERATED! DO NOT EDIT!

import tomllib
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from ai_index.const import validation_config_path, validation_results_path
from .run_validation import _make_run_name
from .utils import (
    discover_completed_runs,
    load_matches,
    matches_to_ranked_lists,
    load_ad_categories,
    build_arm_table,
    build_pairwise_matrix,
    print_arm_table,
    compute_pairwise,
    plot_arm_bars,
    plot_stage_comparison,
    plot_pairwise_matrix,
    plot_pairwise_heatmap,
    plot_stratified_dotplot,
    plot_onet_distribution,
    plot_kl_divergence_bars,
    save_fig,
)

def analyze(run_def: str) -> "Path":
    """Run validation analysis for the given run definition."""
    with open(validation_config_path, "rb") as f:
        config = tomllib.load(f)
    
    completed = discover_completed_runs(run_def)
    
    if not completed:
        raise ValueError(
            f"No completed validation runs found for run definition '{run_def}'.\n"
            f"Run: uv run validate-all {run_def}"
        )
    
    rbo_p = config["rbo_p"]
    fixed_llms = config["fixed_llms"]
    fixed_embeddings = config["fixed_embeddings"]
    completed_names = {rn for rn, _, _, _ in completed}
    
    output_dir = validation_results_path / run_def
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = output_dir / "figures"
    all_llm_dfs = []
    
    for fixed_embed in fixed_embeddings:
        print(f"\n{'#' * 70}")
        print(f"Fixed embedding: {fixed_embed}")
        print(f"{'#' * 70}")
    
        for ref_llm in fixed_llms:
            ref_run = _make_run_name(run_def, ref_llm, fixed_embed)
            if ref_run not in completed_names:
                print(f"\n  Skipping reference LLM {ref_llm} (run not complete)")
                continue
    
            arm_df = build_arm_table(
                completed, config, run_def, "llm", fixed_embed, ref_llm, rbo_p,
            )
    
            title = f"Vary LLM (embed={fixed_embed}, ref={ref_llm})"
            print_arm_table(arm_df, title)
    
            # Plots
            fig_suffix = f"{fixed_embed}__{ref_llm}"
    
            fig = plot_arm_bars(arm_df, title)
            if fig:
                save_fig(fig, figures_dir, f"llm_bars__{fig_suffix}")
    
            fig = plot_stage_comparison(arm_df, title)
            if fig:
                save_fig(fig, figures_dir, f"llm_stage__{fig_suffix}")
    
            fig = plot_kl_divergence_bars(arm_df, title)
            if fig:
                save_fig(fig, figures_dir, f"llm_kl__{fig_suffix}")
    
            # Collect for CSV
            if not arm_df.empty:
                arm_df = arm_df.copy()
                arm_df["fixed_embed"] = fixed_embed
                arm_df["ref_llm"] = ref_llm
                all_llm_dfs.append(arm_df)
    
        # Pairwise matrix: every LLM vs every other LLM (no reference bias)
        for stage in ("cosine", "filtered"):
            matrix = build_pairwise_matrix(completed, "llm", fixed_embed, stage)
            if not matrix.empty:
                mean_agree = (matrix.sum(axis=1) - 1) / (len(matrix) - 1)
                print(f"\nPairwise Top-1 Agreement ({stage}, embed={fixed_embed})")
                print(matrix.to_string(float_format=lambda x: f"{x:.3f}"))
                print(f"\nMean agreement per LLM ({stage}):")
                for model, val in mean_agree.sort_values(ascending=False).items():
                    print(f"  {model:<28s} {val:.4f}")
    
                fig = plot_pairwise_matrix(
                    matrix, f"LLM Pairwise Top-1 ({stage}, embed={fixed_embed})")
                if fig:
                    save_fig(fig, figures_dir, f"llm_pairwise__{fixed_embed}__{stage}")
    all_embed_dfs = []
    
    for fixed_llm in fixed_llms:
        print(f"\n{'#' * 70}")
        print(f"Fixed LLM: {fixed_llm}")
        print(f"{'#' * 70}")
    
        for ref_embed in fixed_embeddings:
            ref_run = _make_run_name(run_def, fixed_llm, ref_embed)
            if ref_run not in completed_names:
                print(f"\n  Skipping reference embedding {ref_embed} (run not complete)")
                continue
    
            arm_df = build_arm_table(
                completed, config, run_def, "embed", fixed_llm, ref_embed, rbo_p,
            )
    
            title = f"Vary Embedding (llm={fixed_llm}, ref={ref_embed})"
            print_arm_table(arm_df, title)
    
            # Plots
            fig_suffix = f"{fixed_llm}__{ref_embed}"
    
            fig = plot_arm_bars(arm_df, title)
            if fig:
                save_fig(fig, figures_dir, f"embed_bars__{fig_suffix}")
    
            fig = plot_stage_comparison(arm_df, title)
            if fig:
                save_fig(fig, figures_dir, f"embed_stage__{fig_suffix}")
    
            fig = plot_kl_divergence_bars(arm_df, title)
            if fig:
                save_fig(fig, figures_dir, f"embed_kl__{fig_suffix}")
    
            # Collect for CSV
            if not arm_df.empty:
                arm_df = arm_df.copy()
                arm_df["fixed_llm"] = fixed_llm
                arm_df["ref_embed"] = ref_embed
                all_embed_dfs.append(arm_df)
    
        # Pairwise matrix: every embedding vs every other embedding
        for stage in ("cosine", "filtered"):
            matrix = build_pairwise_matrix(completed, "embed", fixed_llm, stage)
            if not matrix.empty:
                mean_agree = (matrix.sum(axis=1) - 1) / (len(matrix) - 1)
                print(f"\nPairwise Top-1 Agreement ({stage}, llm={fixed_llm})")
                print(matrix.to_string(float_format=lambda x: f"{x:.3f}"))
                print(f"\nMean agreement per embedding ({stage}):")
                for model, val in mean_agree.sort_values(ascending=False).items():
                    print(f"  {model:<28s} {val:.4f}")
    
                fig = plot_pairwise_matrix(
                    matrix, f"Embedding Pairwise Top-1 ({stage}, llm={fixed_llm})")
                if fig:
                    save_fig(fig, figures_dir, f"embed_pairwise__{fixed_llm}__{stage}")
    fig = plot_pairwise_heatmap(completed)
    if fig:
        save_fig(fig, figures_dir, "pairwise_heatmap")
    if len(completed) >= 2:
        run_a, _, llm_a, embed_a = completed[0]
        run_b, _, llm_b, embed_b = completed[1]
    
        sets_a = matches_to_ranked_lists(load_matches(run_a, "filtered"))
        sets_b = matches_to_ranked_lists(load_matches(run_b, "filtered"))
    
        common_ids = list(set(sets_a) & set(sets_b))
        if common_ids:
            categories = load_ad_categories(common_ids)
            fig = plot_stratified_dotplot(
                sets_a, sets_b, categories,
                f"{run_a} vs {run_b}",
            )
            if fig:
                save_fig(fig, figures_dir, "stratified_dotplot")
    
        fig = plot_onet_distribution(
            sets_a, sets_b,
            ref_label=f"{llm_a}/{embed_a}",
            other_label=f"{llm_b}/{embed_b}",
        )
        if fig:
            save_fig(fig, figures_dir, "onet_distribution")
    if all_llm_dfs:
        llm_path = output_dir / "llm_sensitivity.csv"
        pd.concat(all_llm_dfs, ignore_index=True).to_csv(llm_path, index=False)
        print(f"\nSaved: {llm_path}")
    if all_embed_dfs:
        embed_path = output_dir / "embed_sensitivity.csv"
        pd.concat(all_embed_dfs, ignore_index=True).to_csv(embed_path, index=False)
        print(f"Saved: {embed_path}")
    
    print(f"\nAll results saved to {output_dir}")
    
    return output_dir
