# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/validation/run_all.ipynb

__all__ = ['main', 'plan_runs']

# %% nbs/validation/run_all.ipynb 2
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

from ai_index.const import validation_config_path
from .run_validation import _make_run_name, _is_run_complete

# %% nbs/validation/run_all.ipynb 3
def _load_validation_config() -> dict:
    """Load the validation crossed-design config from config/validation.toml."""
    with open(validation_config_path, "rb") as f:
        return tomllib.load(f)

# %% nbs/validation/run_all.ipynb 4
def plan_runs(config: dict) -> list[tuple[str, str]]:
    """Generate crossed (llm, embed) pairs from the validation config.

    Arm 1: fix embedding, vary LLMs.
    Arm 2: fix LLM, vary embeddings.
    De-duplicates the reference pair that appears in both arms.
    """
    fixed_embed = config["fixed_embedding"]
    fixed_llm = config["fixed_llm"]
    llm_models = config["llm_models"]
    embed_models = config["embed_models"]

    seen = set()
    pairs = []

    # Arm 1: fix embedding, vary LLMs
    for llm in llm_models:
        key = (llm, fixed_embed)
        if key not in seen:
            seen.add(key)
            pairs.append(key)

    # Arm 2: fix LLM, vary embeddings
    for embed in embed_models:
        key = (fixed_llm, embed)
        if key not in seen:
            seen.add(key)
            pairs.append(key)

    return pairs

# %% nbs/validation/run_all.ipynb 5
def _completed_runs(run_def: str, pairs: list[tuple[str, str]]) -> set[tuple[str, str]]:
    """Return the subset of pairs whose validation runs are already complete."""
    return {
        (llm, embed) for llm, embed in pairs
        if _is_run_complete(_make_run_name(run_def, llm, embed))
    }

# %% nbs/validation/run_all.ipynb 6
def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = [a for a in sys.argv[1:] if a.startswith("--")]
    dry_run = "--dry-run" in flags
    force = "--force" in flags

    if len(args) != 1:
        print(
            "Usage: uv run validate-all <run_def_name> [--dry-run] [--force]",
            file=sys.stderr,
        )
        sys.exit(1)

    run_def = args[0]

    config = _load_validation_config()
    pairs = plan_runs(config)
    done = _completed_runs(run_def, pairs)

    print(f"Run definition: {run_def}")
    print(f"Validation runs: {len(pairs)} total, {len(done)} complete, {len(pairs) - len(done)} remaining")
    if done:
        print(f"  Completed: {', '.join(_make_run_name(run_def, l, e) for l, e in sorted(done))}")

    remaining = [(l, e) for l, e in pairs if force or (l, e) not in done]

    if not remaining:
        print("\nAll validation runs already complete.")
        return

    print(f"\nPlanned runs ({len(remaining)}):")
    for i, (llm, embed) in enumerate(remaining, 1):
        status = "(done, --force)" if (llm, embed) in done else "(pending)"
        print(f"  {i:>2}. {_make_run_name(run_def, llm, embed)} {status}")

    if dry_run:
        print("\n--dry-run: no validation runs executed.")
        return

    run_validation_bin = shutil.which("run-validation")
    if run_validation_bin is None:
        print("ERROR: 'run-validation' not found on PATH. Is the package installed?", file=sys.stderr)
        sys.exit(1)

    print()
    failures = []
    for i, (llm, embed) in enumerate(remaining, 1):
        run_name = _make_run_name(run_def, llm, embed)
        print(f"{'=' * 70}")
        print(f"Run {i}/{len(remaining)}: {run_name}")
        print(f"{'=' * 70}")

        cmd = [run_validation_bin, run_def, llm, embed]
        if force:
            cmd.append("--force")

        result = subprocess.run(cmd)
        if result.returncode != 0:
            print(f"\nERROR: run-validation failed for {run_name} (exit code {result.returncode})")
            failures.append((run_name, result.returncode))

        print()

    if failures:
        print(f"\n{len(failures)}/{len(remaining)} validation runs failed:")
        for run_name, code in failures:
            print(f"  - {run_name} (exit code {code})")
        sys.exit(1)

    print(f"All {len(remaining)} validation runs complete.")
