# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/validation/utils.ipynb

__all__ = ['build_arm_table', 'build_pairwise_matrix', 'compute_pairwise', 'discover_completed_runs', 'load_ad_categories', 'load_matches', 'matches_to_ranked_lists', 'mean_rbo', 'onet_distribution_divergence', 'plot_arm_bars', 'plot_kl_divergence_bars', 'plot_onet_distribution', 'plot_pairwise_heatmap', 'plot_pairwise_matrix', 'plot_stage_comparison', 'plot_stratified_dotplot', 'print_arm_table', 'rbo', 'save_fig', 'stratified_agreement', 'top1_agreement', 'topk_jaccard']

# %% nbs/validation/utils.ipynb 3
import tomllib
from collections import Counter
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from ai_index.const import (
    adzuna_db_path,
    pipeline_store_path,
    validation_config_path,
    validation_results_path,
)
from .run_validation import _make_run_name

# %% nbs/validation/utils.ipynb 5
def load_matches(run_name: str, stage: str = "filtered") -> pd.DataFrame:
    """Load match results for a validation run.

    Args:
        run_name: Validation run name (e.g. val__validation_5k__qwen-7b-sbatch__bge-large-sbatch).
        stage: 'filtered' for llm_filter output, 'cosine' for cosine_match output.

    Returns:
        DataFrame with columns: ad_id, rank, onet_code, onet_title,
        role_score, taskskill_score, combined_score.
    """
    if stage == "filtered":
        path = pipeline_store_path / run_name / "llm_filter_candidates" / "filtered_matches.parquet"
    elif stage == "cosine":
        path = pipeline_store_path / run_name / "cosine_candidates" / "candidates.parquet"
    else:
        raise ValueError(f"Unknown stage {stage!r}, expected 'filtered' or 'cosine'")
    return pd.read_parquet(path)

# %% nbs/validation/utils.ipynb 6
def matches_to_ranked_lists(df: pd.DataFrame) -> dict[int, list[str]]:
    """Convert a matches DataFrame to {ad_id: [onet_codes ordered by rank]}.

    Only includes ads that have at least one match.
    """
    result = {}
    for ad_id, group in df.sort_values("rank").groupby("ad_id"):
        result[ad_id] = group["onet_code"].tolist()
    return result

# %% nbs/validation/utils.ipynb 7
def discover_completed_runs(run_def: str | None = None) -> list[tuple[str, str, str, str, str | None]]:
    """Scan store/pipeline/ for completed validation runs.

    Args:
        run_def: If given, only return runs matching this run definition name.

    Returns list of (run_name, run_def, llm_key, embed_key, rerank_key) tuples.
    rerank_key is None for runs that used the default reranker.
    """
    runs = []
    if not pipeline_store_path.exists():
        return runs

    for run_dir in sorted(pipeline_store_path.iterdir()):
        if not run_dir.name.startswith("val__"):
            continue
        exposure = run_dir / "compute_job_ad_exposure" / "ad_exposure.parquet"
        if not exposure.exists():
            continue
        parts = run_dir.name.split("__")
        if len(parts) == 4:
            _, rd, llm, embed = parts
            rerank = None
        elif len(parts) == 5:
            _, rd, llm, embed, rerank = parts
        else:
            continue
        if run_def is not None and rd != run_def:
            continue
        runs.append((run_dir.name, rd, llm, embed, rerank))

    return runs

# %% nbs/validation/utils.ipynb 8
def load_ad_categories(ad_ids: list[int]) -> pd.DataFrame:
    """Load category_name for given ad IDs from adzuna.duckdb.

    Returns DataFrame with columns: ad_id, category_name.
    """
    import duckdb

    con = duckdb.connect(str(adzuna_db_path), read_only=True)
    id_list = ",".join(str(i) for i in ad_ids)
    df = con.sql(f"SELECT id AS ad_id, category_name FROM ads WHERE id IN ({id_list})").df()
    con.close()
    return df

# %% nbs/validation/utils.ipynb 10
def top1_agreement(sets_a: dict[int, list[str]], sets_b: dict[int, list[str]]) -> float:
    """Fraction of ads where the top-1 O*NET match agrees between two runs.

    Only considers ads present in both sets.
    """
    common = set(sets_a) & set(sets_b)
    if not common:
        return 0.0
    agree = sum(1 for ad_id in common if sets_a[ad_id][0] == sets_b[ad_id][0])
    return agree / len(common)

# %% nbs/validation/utils.ipynb 11
def topk_jaccard(sets_a: dict[int, list[str]], sets_b: dict[int, list[str]]) -> float:
    """Mean Jaccard similarity of top-K O*NET match sets across ads.

    For each ad, Jaccard = |A & B| / |A | B|. Averaged over common ads.
    """
    common = set(sets_a) & set(sets_b)
    if not common:
        return 0.0
    total = 0.0
    for ad_id in common:
        a = set(sets_a[ad_id])
        b = set(sets_b[ad_id])
        union = a | b
        if union:
            total += len(a & b) / len(union)
    return total / len(common)

# %% nbs/validation/utils.ipynb 12
def rbo(list_a: list[str], list_b: list[str], p: float = 0.9) -> float:
    """Rank-Biased Overlap for two ranked lists (Webber et al. 2010).

    Computes RBO_EXT which extrapolates agreement at the evaluation depth.
    For identical lists this returns ~1.0; for disjoint lists ~0.0.
    """
    k = max(len(list_a), len(list_b))
    if k == 0:
        return 1.0

    set_a = set()
    set_b = set()
    agreements = []
    for d in range(1, k + 1):
        if d <= len(list_a):
            set_a.add(list_a[d - 1])
        if d <= len(list_b):
            set_b.add(list_b[d - 1])
        agreements.append(len(set_a & set_b) / d)

    rbo_min = 0.0
    for d in range(1, k + 1):
        rbo_min += (p ** (d - 1)) * agreements[d - 1]
    rbo_min *= (1 - p)

    return rbo_min + (p ** k) * agreements[-1]

# %% nbs/validation/utils.ipynb 13
def mean_rbo(sets_a: dict[int, list[str]], sets_b: dict[int, list[str]], p: float = 0.9) -> float:
    """Mean RBO across all common ads."""
    common = set(sets_a) & set(sets_b)
    if not common:
        return 0.0
    total = sum(rbo(sets_a[ad_id], sets_b[ad_id], p) for ad_id in common)
    return total / len(common)

# %% nbs/validation/utils.ipynb 14
def onet_distribution_divergence(
    sets_a: dict[int, list[str]], sets_b: dict[int, list[str]]
) -> dict:
    """Compare top-1 O*NET assignment distributions between two runs.

    Returns dict with chi2_statistic, chi2_pvalue, kl_divergence.
    """
    from scipy import stats

    common = set(sets_a) & set(sets_b)

    counts_a = Counter(sets_a[ad_id][0] for ad_id in common)
    counts_b = Counter(sets_b[ad_id][0] for ad_id in common)

    all_codes = sorted(set(counts_a) | set(counts_b))
    freq_a = np.array([counts_a.get(c, 0) for c in all_codes], dtype=float)
    freq_b = np.array([counts_b.get(c, 0) for c in all_codes], dtype=float)

    chi2_stat, chi2_p = stats.chisquare(freq_a, f_exp=freq_b + 1e-10)

    prob_a = freq_a / freq_a.sum()
    prob_b = freq_b / freq_b.sum()
    prob_b_safe = np.where(prob_b > 0, prob_b, 1e-10)
    prob_a_safe = np.where(prob_a > 0, prob_a, 1e-10)
    kl = float(np.sum(prob_a_safe * np.log(prob_a_safe / prob_b_safe)))

    return {
        "chi2_statistic": float(chi2_stat),
        "chi2_pvalue": float(chi2_p),
        "kl_divergence": kl,
        "n_unique_codes_a": len(counts_a),
        "n_unique_codes_b": len(counts_b),
        "n_common_ads": len(common),
    }

# %% nbs/validation/utils.ipynb 15
def stratified_agreement(
    sets_a: dict[int, list[str]],
    sets_b: dict[int, list[str]],
    categories: pd.DataFrame,
) -> pd.DataFrame:
    """Compute top-1 agreement and Jaccard stratified by Adzuna category.

    Returns DataFrame with columns: category, n_ads, top1_agreement, jaccard.
    """
    common = set(sets_a) & set(sets_b)
    cat_map = dict(zip(categories["ad_id"], categories["category_name"]))

    by_cat: dict[str, list[int]] = {}
    for ad_id in common:
        cat = cat_map.get(ad_id, "Unknown")
        by_cat.setdefault(cat, []).append(ad_id)

    rows = []
    for cat, ad_ids in sorted(by_cat.items()):
        sub_a = {i: sets_a[i] for i in ad_ids}
        sub_b = {i: sets_b[i] for i in ad_ids}
        rows.append({
            "category": cat,
            "n_ads": len(ad_ids),
            "top1_agreement": top1_agreement(sub_a, sub_b),
            "jaccard": topk_jaccard(sub_a, sub_b),
        })

    return pd.DataFrame(rows)

# %% nbs/validation/utils.ipynb 17
def compute_pairwise(
    run_a: str, run_b: str, stage: str = "filtered", rbo_p: float = 0.9
) -> dict:
    """Compute all pairwise statistics between two validation runs.

    Returns dict with top1, jaccard, rbo, divergence stats.
    """
    df_a = load_matches(run_a, stage)
    df_b = load_matches(run_b, stage)
    sets_a = matches_to_ranked_lists(df_a)
    sets_b = matches_to_ranked_lists(df_b)

    result = {
        "run_a": run_a,
        "run_b": run_b,
        "stage": stage,
        "n_common_ads": len(set(sets_a) & set(sets_b)),
        "top1_agreement": top1_agreement(sets_a, sets_b),
        "jaccard": topk_jaccard(sets_a, sets_b),
        "rbo": mean_rbo(sets_a, sets_b, rbo_p),
    }

    div = onet_distribution_divergence(sets_a, sets_b)
    result.update(div)

    return result

# %% nbs/validation/utils.ipynb 18
def build_arm_table(
    completed_runs: list[tuple[str, str, str, str, str | None]],
    config: dict,
    run_def: str,
    vary: str,
    fixed_models: dict,
    ref_model: str,
    rbo_p: float = 0.9,
) -> pd.DataFrame:
    """Build a sensitivity table for one arm, with both cosine and filtered stage stats.

    Args:
        vary: "llm", "embed", or "rerank" -- which model dimension to vary.
        fixed_models: Dict of the models held constant. Keys are the other dimensions.
            For vary="llm": {"embed": "...", "rerank": None}
            For vary="embed": {"llm": "...", "rerank": None}
            For vary="rerank": {"llm": "...", "embed": "..."}
        ref_model: The reference model within the varied dimension.

    Returns DataFrame with columns: model, cosine_top1, cosine_jaccard, cosine_rbo,
        filtered_top1, filtered_jaccard, filtered_rbo, filtered_kl.
    """
    if vary == "llm":
        ref_run = _make_run_name(run_def, ref_model, fixed_models["embed"], fixed_models.get("rerank"))
        models = config["llm_models"]
    elif vary == "embed":
        ref_run = _make_run_name(run_def, fixed_models["llm"], ref_model, fixed_models.get("rerank"))
        models = config["embed_models"]
    elif vary == "rerank":
        ref_run = _make_run_name(run_def, fixed_models["llm"], fixed_models["embed"], ref_model)
        models = config["rerank_models"]
    else:
        raise ValueError(f"vary must be 'llm', 'embed', or 'rerank', got {vary!r}")

    run_lookup = {(llm, embed, rerank): rn for rn, _, llm, embed, rerank in completed_runs}

    rows = []
    for model in models:
        if vary == "llm":
            key = (model, fixed_models["embed"], fixed_models.get("rerank"))
        elif vary == "embed":
            key = (fixed_models["llm"], model, fixed_models.get("rerank"))
        elif vary == "rerank":
            key = (fixed_models["llm"], fixed_models["embed"], model)

        if key not in run_lookup:
            continue
        run_name = run_lookup[key]
        if run_name == ref_run:
            continue

        row = {"model": model}

        # Cosine stage (pre-LLM-filter) -- only meaningful when varying embed
        cosine_path_a = pipeline_store_path / ref_run / "cosine_candidates" / "candidates.parquet"
        cosine_path_b = pipeline_store_path / run_name / "cosine_candidates" / "candidates.parquet"
        if cosine_path_a.exists() and cosine_path_b.exists():
            cs = compute_pairwise(ref_run, run_name, "cosine", rbo_p)
            row["cosine_top1"] = cs["top1_agreement"]
            row["cosine_jaccard"] = cs["jaccard"]
            row["cosine_rbo"] = cs["rbo"]

        # Filtered stage (post-LLM-filter)
        fs = compute_pairwise(ref_run, run_name, "filtered", rbo_p)
        row["filtered_top1"] = fs["top1_agreement"]
        row["filtered_jaccard"] = fs["jaccard"]
        row["filtered_rbo"] = fs["rbo"]
        row["filtered_kl"] = fs["kl_divergence"]

        rows.append(row)

    return pd.DataFrame(rows)

# %% nbs/validation/utils.ipynb 19
def print_arm_table(arm_df: pd.DataFrame, title: str):
    """Print a formatted sensitivity table with cosine and filtered stage metrics."""
    if arm_df.empty:
        print(f"\n{title}: no completed runs")
        return

    print(f"\n{title}")
    print("=" * 110)
    model_w = max(len(m) for m in arm_df["model"]) + 2
    has_cosine = "cosine_top1" in arm_df.columns and arm_df["cosine_top1"].notna().any()

    if has_cosine:
        header = (
            f"{'Model':<{model_w}} "
            f"{'Cos Top1':>10} {'Cos Jacc':>10} "
            f"{'Filt Top1':>10} {'Filt Jacc':>10} {'Filt RBO':>10} {'Filt KL':>10}"
        )
    else:
        header = (
            f"{'Model':<{model_w}} "
            f"{'Filt Top1':>10} {'Filt Jacc':>10} {'Filt RBO':>10} {'Filt KL':>10}"
        )
    print(header)
    print("-" * len(header))
    for _, row in arm_df.iterrows():
        if has_cosine:
            print(
                f"{row['model']:<{model_w}} "
                f"{row['cosine_top1']:>10.4f} {row['cosine_jaccard']:>10.4f} "
                f"{row['filtered_top1']:>10.4f} {row['filtered_jaccard']:>10.4f} "
                f"{row['filtered_rbo']:>10.4f} {row['filtered_kl']:>10.4f}"
            )
        else:
            print(
                f"{row['model']:<{model_w}} "
                f"{row['filtered_top1']:>10.4f} {row['filtered_jaccard']:>10.4f} "
                f"{row['filtered_rbo']:>10.4f} {row['filtered_kl']:>10.4f}"
            )

# %% nbs/validation/utils.ipynb 20
def build_pairwise_matrix(
    completed_runs: list[tuple[str, str, str, str, str | None]],
    vary: str,
    fixed_models: dict,
    stage: str = "filtered",
) -> pd.DataFrame:
    """Build an N x N pairwise top-1 agreement matrix for one arm.

    Args:
        vary: "llm", "embed", or "rerank" -- which dimension is being varied.
        fixed_models: Dict of the models held constant (same format as build_arm_table).
        stage: "filtered" or "cosine".

    Returns square DataFrame indexed and columned by model name.
    """
    if vary == "llm":
        arm_runs = [(llm, rn) for rn, _, llm, embed, rerank in completed_runs
                    if embed == fixed_models["embed"] and rerank == fixed_models.get("rerank")]
    elif vary == "embed":
        arm_runs = [(embed, rn) for rn, _, llm, embed, rerank in completed_runs
                    if llm == fixed_models["llm"] and rerank == fixed_models.get("rerank")]
    elif vary == "rerank":
        arm_runs = [(rerank, rn) for rn, _, llm, embed, rerank in completed_runs
                    if llm == fixed_models["llm"] and embed == fixed_models["embed"] and rerank is not None]
    else:
        raise ValueError(f"vary must be 'llm', 'embed', or 'rerank', got {vary!r}")

    if len(arm_runs) < 2:
        return pd.DataFrame()

    models = [label for label, _ in arm_runs]
    ranked = {}
    for label, rn in arm_runs:
        try:
            ranked[label] = matches_to_ranked_lists(load_matches(rn, stage))
        except FileNotFoundError:
            continue

    models = [m for m in models if m in ranked]
    if len(models) < 2:
        return pd.DataFrame()

    n = len(models)
    matrix = pd.DataFrame(1.0, index=models, columns=models)

    for i in range(n):
        for j in range(i + 1, n):
            agreement = top1_agreement(ranked[models[i]], ranked[models[j]])
            matrix.iloc[i, j] = agreement
            matrix.iloc[j, i] = agreement

    return matrix

# %% nbs/validation/utils.ipynb 22
def plot_arm_bars(arm_df: pd.DataFrame, arm_label: str) -> plt.Figure | None:
    """Grouped bar chart of filtered top1/jaccard/RBO per model for one arm."""
    if arm_df.empty:
        return None

    metrics = ["filtered_top1", "filtered_jaccard", "filtered_rbo"]
    labels = ["Top-1 Agreement", "Jaccard", "RBO"]
    x = np.arange(len(arm_df))
    width = 0.25

    fig, ax = plt.subplots(figsize=(max(10, len(arm_df) * 1.2), 5))
    for i, (metric, label) in enumerate(zip(metrics, labels)):
        ax.bar(x + i * width, arm_df[metric].values, width, label=label)

    ax.set_xlabel("Model")
    ax.set_ylabel("Agreement Score (filtered)")
    ax.set_title(f"Model Sensitivity: {arm_label}")
    ax.set_xticks(x + width)
    ax.set_xticklabels(arm_df["model"].values, rotation=45, ha="right")
    ax.legend()
    ax.set_ylim(0, 1.05)
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 23
def plot_stage_comparison(arm_df: pd.DataFrame, arm_label: str) -> plt.Figure | None:
    """Side-by-side bars showing cosine vs filtered top-1 agreement per model."""
    if arm_df.empty or "cosine_top1" not in arm_df.columns:
        return None

    sub = arm_df.dropna(subset=["cosine_top1"])
    if sub.empty:
        return None

    x = np.arange(len(sub))
    width = 0.35

    fig, ax = plt.subplots(figsize=(max(10, len(sub) * 1.2), 5))
    ax.bar(x - width / 2, sub["cosine_top1"].values, width, label="Cosine stage")
    ax.bar(x + width / 2, sub["filtered_top1"].values, width, label="Filtered stage")

    ax.set_xlabel("Model")
    ax.set_ylabel("Top-1 Agreement vs Reference")
    ax.set_title(f"Stage Comparison: {arm_label}")
    ax.set_xticks(x)
    ax.set_xticklabels(sub["model"].values, rotation=45, ha="right")
    ax.legend()
    ax.set_ylim(0, 1.05)
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 24
def plot_pairwise_matrix(matrix: pd.DataFrame, title: str) -> plt.Figure | None:
    """Annotated heatmap of a pairwise agreement matrix."""
    if matrix.empty:
        return None

    n = len(matrix)
    fig, ax = plt.subplots(figsize=(max(8, n * 0.9), max(6, n * 0.7)))
    im = ax.imshow(matrix.values, vmin=0, vmax=1, cmap="YlOrRd")
    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    ax.set_xticklabels(matrix.columns, rotation=90, fontsize=8)
    ax.set_yticklabels(matrix.index, fontsize=8)

    for i in range(n):
        for j in range(n):
            ax.text(j, i, f"{matrix.iloc[i, j]:.2f}",
                    ha="center", va="center", fontsize=7)

    ax.set_title(title)
    fig.colorbar(im)
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 25
def plot_pairwise_heatmap(
    completed_runs: list[tuple[str, str, str, str]],
) -> plt.Figure | None:
    """Pairwise top-1 agreement heatmap across all completed runs."""
    if len(completed_runs) < 2:
        return None

    run_names = [rn for rn, *_ in completed_runs]
    n = len(run_names)
    matrix = np.ones((n, n))

    for i in range(n):
        for j in range(i + 1, n):
            stats = compute_pairwise(run_names[i], run_names[j], "filtered")
            matrix[i, j] = stats["top1_agreement"]
            matrix[j, i] = stats["top1_agreement"]

    fig, ax = plt.subplots(figsize=(max(8, n * 0.8), max(6, n * 0.6)))
    im = ax.imshow(matrix, vmin=0, vmax=1, cmap="YlOrRd")
    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    short_labels = [rn.replace("val__", "") for rn in run_names]
    ax.set_xticklabels(short_labels, rotation=90, fontsize=7)
    ax.set_yticklabels(short_labels, fontsize=7)
    ax.set_title("Pairwise Top-1 Agreement")
    fig.colorbar(im)
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 26
def plot_stratified_dotplot(
    sets_a: dict[int, list[str]],
    sets_b: dict[int, list[str]],
    categories: pd.DataFrame,
    pair_label: str,
) -> plt.Figure | None:
    """Dot plot of top-1 agreement by category, dot size = n_ads."""
    strat = stratified_agreement(sets_a, sets_b, categories)
    if strat.empty:
        return None

    strat = strat.sort_values("top1_agreement")
    fig, ax = plt.subplots(figsize=(10, max(5, len(strat) * 0.4)))
    sizes = (strat["n_ads"] / strat["n_ads"].max()) * 300 + 20
    ax.scatter(strat["top1_agreement"], range(len(strat)), s=sizes, alpha=0.7)
    ax.set_yticks(range(len(strat)))
    ax.set_yticklabels(strat["category"].values)
    ax.set_xlabel("Top-1 Agreement")
    ax.set_title(f"Agreement by Category: {pair_label}")
    ax.set_xlim(-0.05, 1.05)
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 27
def plot_onet_distribution(
    sets_ref: dict[int, list[str]],
    sets_other: dict[int, list[str]],
    ref_label: str,
    other_label: str,
    top_n: int = 20,
) -> plt.Figure | None:
    """Grouped bar chart of top-N most-assigned O*NET codes."""
    common = set(sets_ref) & set(sets_other)
    if not common:
        return None

    counts_ref = Counter(sets_ref[i][0] for i in common)
    counts_other = Counter(sets_other[i][0] for i in common)

    top_codes = [c for c, _ in counts_ref.most_common(top_n)]
    ref_vals = [counts_ref.get(c, 0) for c in top_codes]
    other_vals = [counts_other.get(c, 0) for c in top_codes]

    x = np.arange(len(top_codes))
    width = 0.35

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.bar(x - width / 2, ref_vals, width, label=ref_label)
    ax.bar(x + width / 2, other_vals, width, label=other_label)
    ax.set_xlabel("O*NET Code")
    ax.set_ylabel("Count (top-1 assignments)")
    ax.set_title(f"O*NET Distribution: Top {top_n} Codes")
    ax.set_xticks(x)
    ax.set_xticklabels(top_codes, rotation=90, fontsize=7)
    ax.legend()
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 28
def plot_kl_divergence_bars(arm_df: pd.DataFrame, arm_label: str) -> plt.Figure | None:
    """Bar chart of KL divergence per model for one arm."""
    if arm_df.empty:
        return None

    fig, ax = plt.subplots(figsize=(max(10, len(arm_df) * 1.0), 5))
    ax.bar(range(len(arm_df)), arm_df["filtered_kl"].values)
    ax.set_xlabel("Model")
    ax.set_ylabel("KL Divergence")
    ax.set_title(f"KL Divergence vs Reference: {arm_label}")
    ax.set_xticks(range(len(arm_df)))
    ax.set_xticklabels(arm_df["model"].values, rotation=45, ha="right")
    fig.tight_layout()
    return fig

# %% nbs/validation/utils.ipynb 30
def save_fig(fig: plt.Figure, output_dir: Path, name: str) -> Path:
    """Save figure to output directory as PNG. Returns the saved path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{name}.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path
