# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/utils/observe/models.ipynb

__all__ = ['ControlResponse', 'EdgeStatus', 'EpochInfo', 'InjectDataRequest', 'LogEntry', 'NetStatus', 'NodeStatus', 'SendControlRequest']

# %% nbs/ai_index/utils/observe/models.ipynb 2
from pydantic import BaseModel

# %% nbs/ai_index/utils/observe/models.ipynb 3
class NetStatus(BaseModel):
    """Overall status of the net."""
    node_names: list[str]
    edge_count: int
    total_epochs: int
    epochs_by_state: dict[str, int]
    busy_nodes: list[str]
    idle_nodes: list[str]


class NodeStatus(BaseModel):
    """Status of a single node."""
    name: str
    enabled: bool
    epoch_count: int
    is_busy: bool
    running_epoch_ids: list[str]
    startable_epoch_ids: list[str]
    in_ports: list[str]
    out_ports: list[str]


class EpochInfo(BaseModel):
    """Information about a single epoch."""
    epoch_id: str
    node_name: str
    state: str
    was_cancelled: bool
    was_cache_hit: bool
    created_at: str | None = None
    started_at: str | None = None
    ended_at: str | None = None
    duration_seconds: float | None = None
    pool_worker_label: str | None = None


class EdgeStatus(BaseModel):
    """Status of a single edge."""
    source_node: str
    source_port: str
    target_node: str
    target_port: str
    packet_count: int


class LogEntry(BaseModel):
    """A single log entry."""
    timestamp: str
    message: str
    node_name: str | None = None
    epoch_id: str | None = None


class SendControlRequest(BaseModel):
    """Request to send a control command to a node."""
    node_name: str
    control_type: str
    value: str | int | None = None


class InjectDataRequest(BaseModel):
    """Request to inject data into a node's input port."""
    node_name: str
    port_name: str
    values: list


class ControlResponse(BaseModel):
    """Response from a control action."""
    ok: bool
    message: str
