# Defaults

[defaults.api]
batch_size = 1000

[defaults.local]
device = "cuda"
dtype = "float16"
batch_size = 64

[defaults.sbatch]
dtype = "float16"
batch_size = 64
job_name = "embed"
time = "01:00:00"
setup = false

# Models

[models."text-embedding-3-small"]
mode = "api"
model = "text-embedding-3-small"

[models.bge-large-local]
mode = "local"
model = "BAAI/bge-large-en-v1.5"

[models.bge-large-sbatch]
mode = "sbatch"
model = "BAAI/bge-large-en-v1.5"
