# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ai_index/utils/prompts.ipynb

__all__ = ['load_prompt']

# %% nbs/ai_index/utils/prompts.ipynb 2
from pathlib import Path

from .. import const


def load_prompt(prompt_path: str) -> str:
    """Load a prompt template from the prompt library.

    Args:
        prompt_path: Slash-separated path relative to ``config/prompt_library/``,
            e.g. ``"llm_summarise/main/system"`` resolves to
            ``config/prompt_library/llm_summarise/main/system.md``.

    Returns:
        The prompt text (with leading/trailing whitespace stripped).

    Raises:
        FileNotFoundError: If the resolved ``.md`` file does not exist.
    """
    file_path = const.repo_root / "config" / "prompt_library" / f"{prompt_path}.md"
    if not file_path.is_file():
        raise FileNotFoundError(f"Prompt not found: {file_path}")
    return file_path.read_text().strip()
