# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/llm_runner/embed.ipynb

__all__ = ['run_embeddings']

# %% nbs/llm_runner/embed.ipynb 2
import numpy as np

from .models import load_embedding_model

# %% nbs/llm_runner/embed.ipynb 3
def run_embeddings(texts: list[str], *, model_name: str = "BAAI/bge-large-en-v1.5",
                   device: str = "cuda", dtype: str = "float16",
                   batch_size: int = 64) -> np.ndarray:
    """Embed a list of texts using a SentenceTransformer model.

    Args:
        texts: List of strings to embed.
        model_name: HuggingFace model ID.
        device: Device ("cuda", "cpu").
        dtype: Model precision ("float16", "bfloat16", "float32").
        batch_size: Batch size for encoding.

    Returns:
        numpy array of shape (len(texts), embedding_dim) with the specified dtype.
    """
    model = load_embedding_model(
        model_name, device=device, dtype=dtype,
        offline=(device != "cpu"),
    )
    embeddings = model.encode(texts, batch_size=batch_size)

    # Cast to target dtype
    target_np_dtype = {"float16": np.float16, "bfloat16": np.float32, "float32": np.float32}[dtype]
    return embeddings.astype(target_np_dtype)
