# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/llm_runner/embed.ipynb

__all__ = ['run_embeddings']

# %% nbs/llm_runner/embed.ipynb 2
import numpy as np

from .models import load_embedding_model

# %% nbs/llm_runner/embed.ipynb 3
def run_embeddings(texts: list[str], *, model_name: str = "BAAI/bge-large-en-v1.5",
                   device: str = "cuda", dtype: str = "float16",
                   batch_size: int = 64,
                   max_seq_length: int | None = None,
                   prompt: str | None = None,
                   prompt_name: str | None = None,
                   st_kwargs: dict | None = None) -> np.ndarray:
    """Embed a list of texts using a SentenceTransformer model.

    Args:
        texts: List of strings to embed.
        model_name: HuggingFace model ID.
        device: Device ("cuda", "cpu").
        dtype: Model precision ("float16", "bfloat16", "float32").
        batch_size: Batch size for encoding.
        max_seq_length: If set, override the model's max_seq_length to clamp
            worst-case memory usage. Essential for large instruction-following
            models like Qwen3-Embedding-8B whose native max is 40960 tokens.
        prompt: Optional instruction string prepended to each text. Used by
            instruction-following embedding models (e.g. Qwen3-Embedding).
        prompt_name: Optional named prompt from the model's config (e.g. "query").
            Mutually exclusive with prompt.
        st_kwargs: Extra kwargs passed to the SentenceTransformer constructor.

    Returns:
        numpy array of shape (len(texts), embedding_dim) with the specified dtype.
    """
    model = load_embedding_model(
        model_name, device=device, dtype=dtype,
        offline=(device != "cpu"),
        st_kwargs=st_kwargs,
    )
    if max_seq_length is not None:
        model.max_seq_length = max_seq_length
    encode_kwargs = {}
    if prompt is not None:
        encode_kwargs["prompt"] = prompt
    if prompt_name is not None:
        encode_kwargs["prompt_name"] = prompt_name
    embeddings = model.encode(texts, batch_size=batch_size, **encode_kwargs)

    # Cast to target dtype
    target_np_dtype = {"float16": np.float16, "bfloat16": np.float32, "float32": np.float32}[dtype]
    return embeddings.astype(target_np_dtype)
