# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/deploy/destroy.ipynb

__all__ = ['main']

# %% nbs/deploy/destroy.ipynb 2
import subprocess
import sys

from .config import load_deploy_config, server_exists

# %% nbs/deploy/destroy.ipynb 3
def main():
    config = load_deploy_config()
    name = config["server"]["name"]

    if not server_exists(name):
        print(f"Server '{name}' does not exist, nothing to destroy.")
        return

    print(f"Destroying server '{name}'...")
    subprocess.run(
        ["hcloud", "server", "delete", name],
        check=True,
    )
    print(f"Server '{name}' destroyed.")
