# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/deploy/download_store.ipynb

__all__ = ['main']

# %% nbs/deploy/download_store.ipynb 2
import subprocess
import sys

from .config import get_server_ip, load_deploy_config

# %% nbs/deploy/download_store.ipynb 3
def main():
    if len(sys.argv) != 3:
        print("Usage: remote-download-store <remote_rel_store_path> <local_path>", file=sys.stderr)
        sys.exit(1)

    remote_rel = sys.argv[1]
    local_path = sys.argv[2]

    config = load_deploy_config()
    ip = get_server_ip(config["server"]["name"])
    repo_path = config["repo"]["path"]

    remote_full = f"root@{ip}:{repo_path}/store/{remote_rel}"

    print(f"Downloading {remote_full} -> {local_path}")
    subprocess.run(
        ["rsync", "-avz", remote_full, local_path],
        check=True,
    )
