# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/deploy/get_ip.ipynb

__all__ = ['main']

# %% nbs/deploy/get_ip.ipynb 2
import sys

from .config import get_server_ip, load_deploy_config

# %% nbs/deploy/get_ip.ipynb 3
def main():
    config = load_deploy_config()
    ip = get_server_ip(config["server"]["name"])
    print(ip)
