# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/deploy/run_pipeline.ipynb

__all__ = ['REMOTE_LOG', 'REMOTE_PID', 'log', 'start']

# %% nbs/deploy/run_pipeline.ipynb 2
import subprocess
import sys

from .config import get_server_ip, load_deploy_config, run_ssh

REMOTE_LOG = "/root/pipeline.log"
REMOTE_PID = "/root/pipeline.pid"

# %% nbs/deploy/run_pipeline.ipynb 3
def start():
    """Start the pipeline on the remote, detached from SSH."""
    if len(sys.argv) < 2:
        print("Usage: remote-run-pipeline <run_name>", file=sys.stderr)
        sys.exit(1)

    run_name = sys.argv[1]
    config = load_deploy_config()
    ip = get_server_ip(config["server"]["name"])
    repo_path = config["repo"]["path"]

    # Check if a pipeline is already running
    result = run_ssh(ip, f"test -f {REMOTE_PID} && kill -0 $(cat {REMOTE_PID}) 2>/dev/null && echo running || echo stopped",
                     check=False, capture=True)
    if result.stdout.strip() == "running":
        pid = run_ssh(ip, f"cat {REMOTE_PID}", capture=True).stdout.strip()
        print(f"Pipeline already running (PID {pid}). Check progress with: uv run remote-pipeline-log")
        print(f"To kill it: uv run remote-run-cmd kill {pid}")
        sys.exit(1)

    # Start pipeline in background, fully detached from SSH session
    cmd = (
        f"cd {repo_path} && "
        f"nohup /root/.local/bin/uv run --no-dev run-pipeline {run_name} "
        f"> {REMOTE_LOG} 2>&1 </dev/null & echo $! > {REMOTE_PID}"
    )
    subprocess.run(
        ["ssh", "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=10",
         "-f", f"root@{ip}", cmd],
        check=True,
    )
    pid = run_ssh(ip, f"cat {REMOTE_PID}", capture=True).stdout.strip()
    print(f"Pipeline started on remote (PID {pid}, run={run_name})")
    print(f"  Log:      uv run remote-pipeline-log")
    print(f"  Follow:   uv run remote-pipeline-log --follow")
    print(f"  Kill:     uv run remote-run-cmd kill {pid}")


def log():
    """Tail the remote pipeline log."""
    args = sys.argv[1:]
    follow = "--follow" in args or "-f" in args
    args = [a for a in args if a not in ("--follow", "-f")]
    n_lines = int(args[0]) if args else 50

    config = load_deploy_config()
    ip = get_server_ip(config["server"]["name"])

    # Check if running
    result = run_ssh(ip, f"test -f {REMOTE_PID} && kill -0 $(cat {REMOTE_PID}) 2>/dev/null && echo running || echo stopped",
                     check=False, capture=True)
    status = result.stdout.strip()

    if follow:
        print(f"[pipeline {status}] Following {REMOTE_LOG} (Ctrl+C to stop)...")
        subprocess.run(
            ["ssh", "-o", "StrictHostKeyChecking=no",
             f"root@{ip}",
             f"tail -f {REMOTE_LOG}"],
        )
    else:
        print(f"[pipeline {status}] Last {n_lines} lines of {REMOTE_LOG}:")
        print()
        run_ssh(ip, f"tail -n {n_lines} {REMOTE_LOG}")
