# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/calibration/calibrate_all.ipynb

__all__ = ['EMBED_RESULTS_DIR', 'LLM_RESULTS_DIR', 'main', 'plan_runs']

# %% nbs/calibration/calibrate_all.ipynb 2
import asyncio
import shutil
import sys
import tomllib
from pathlib import Path

from ai_index.const import calibration_results_path, llm_models_config_path, embed_models_config_path, pipeline_store_path
from .run_calibration import run_calibration

LLM_RESULTS_DIR = calibration_results_path / "llm"
EMBED_RESULTS_DIR = calibration_results_path / "embed"

# %% nbs/calibration/calibrate_all.ipynb 3
def _get_sbatch_keys(config_path: Path) -> list[str]:
    """Return all model keys with mode='sbatch' from a model TOML config."""
    with open(config_path, "rb") as f:
        cfg = tomllib.load(f)
    return [
        key for key, entry in cfg["models"].items()
        if entry["mode"] == "sbatch"
    ]

# %% nbs/calibration/calibrate_all.ipynb 4
def _calibrated_keys(results_dir: Path) -> set[str]:
    """Return model keys that already have calibration result files."""
    if not results_dir.exists():
        return set()
    return {p.stem for p in results_dir.glob("*.json")}

# %% nbs/calibration/calibrate_all.ipynb 5
def plan_runs(
    all_llm: list[str],
    all_embed: list[str],
    done_llm: set[str],
    done_embed: set[str],
) -> list[tuple[str, str]]:
    """Plan (llm_key, embed_key) pairs to cover all uncalibrated models.

    Pairs uncalibrated LLMs with uncalibrated embeds first, then pairs any
    remaining with an already-calibrated model from the other type.
    """
    need_llm = [k for k in all_llm if k not in done_llm]
    need_embed = [k for k in all_embed if k not in done_embed]

    pairs = []

    # Pair uncalibrated LLMs with uncalibrated embeds
    while need_llm and need_embed:
        pairs.append((need_llm.pop(0), need_embed.pop(0)))

    # Remaining uncalibrated LLMs: pair with a calibrated embed (or first embed)
    if need_llm:
        fallback_embed = next(iter(done_embed), all_embed[0])
        for llm_key in need_llm:
            pairs.append((llm_key, fallback_embed))

    # Remaining uncalibrated embeds: pair with a calibrated LLM (or first LLM)
    if need_embed:
        fallback_llm = next(iter(done_llm), all_llm[0])
        for embed_key in need_embed:
            pairs.append((fallback_llm, embed_key))

    return pairs

# %% nbs/calibration/calibrate_all.ipynb 6
async def _run_all(pairs: list[tuple[str, str]], *, parallel: bool = True) -> list[tuple[str, str]]:
    """Run calibration for all pairs in-process. Returns list of failed (llm, embed) pairs.

    Concurrent access to the shared Adzuna DuckDB is serialized by a
    readers-writer lock in get_adzuna_conn (see adzuna_store.py).
    """
    failures = []

    async def _run_one(i: int, llm: str, embed: str):
        run_name = f"_calibration_{i}" if parallel else "calibration"
        print(f"\n{'=' * 70}")
        print(f"Run {i}/{len(pairs)}: {llm} + {embed}")
        print(f"{'=' * 70}", flush=True)
        try:
            await run_calibration(llm, embed, run_name=run_name)
        except Exception as e:
            print(f"\nERROR: calibration failed for {llm} + {embed}: {e}")
            failures.append((llm, embed))

    tasks = [_run_one(i, llm, embed) for i, (llm, embed) in enumerate(pairs, 1)]
    if parallel:
        await asyncio.gather(*tasks)
    else:
        for task in tasks:
            await task

    return failures

# %% nbs/calibration/calibrate_all.ipynb 7
def main():
    dry_run = "--dry-run" in sys.argv
    sequential = "--sequential" in sys.argv

    all_llm = _get_sbatch_keys(llm_models_config_path)
    all_embed = _get_sbatch_keys(embed_models_config_path)
    done_llm = _calibrated_keys(LLM_RESULTS_DIR)
    done_embed = _calibrated_keys(EMBED_RESULTS_DIR)

    print(f"LLM models:   {len(all_llm)} total, {len(done_llm)} calibrated, {len(all_llm) - len(done_llm)} remaining")
    print(f"Embed models: {len(all_embed)} total, {len(done_embed)} calibrated, {len(all_embed) - len(done_embed)} remaining")

    if done_llm:
        print(f"  LLM done:   {', '.join(sorted(done_llm))}")
    if done_embed:
        print(f"  Embed done: {', '.join(sorted(done_embed))}")

    pairs = plan_runs(all_llm, all_embed, done_llm, done_embed)

    if not pairs:
        print("\nAll models already calibrated.")
        return

    mode = "sequential" if sequential else "parallel"
    print(f"\nPlanned runs ({len(pairs)}, {mode}):")
    for i, (llm, embed) in enumerate(pairs, 1):
        llm_new = "(new)" if llm not in done_llm else "(done)"
        embed_new = "(new)" if embed not in done_embed else "(done)"
        print(f"  {i:>2}. {llm} {llm_new}  +  {embed} {embed_new}")

    if dry_run:
        print("\n--dry-run: no calibrations executed.")
        return

    print()
    failures = asyncio.run(_run_all(pairs, parallel=not sequential))

    # Clean up temporary pipeline store directories from parallel runs
    if not sequential:
        for i in range(1, len(pairs) + 1):
            tmp_store = pipeline_store_path / f"_calibration_{i}"
            if tmp_store.exists():
                shutil.rmtree(tmp_store)

    if failures:
        print(f"\n{len(failures)}/{len(pairs)} calibration runs failed:")
        for llm, embed in failures:
            print(f"  - {llm} + {embed}")
        sys.exit(1)

    print(f"All {len(pairs)} calibration runs complete.")
